// Root types are named through the package's own name, so the emitted cache.d.ts imports them from "@effected/images"
// (kept external by dtsExternals) instead of carrying copies.
import type * as Images from "@effected/images";
import { Context, Effect, Layer, Option, Result } from "effect";
import { ImageBackend } from "./ImageBackend.js";
import type { ImageBackendError } from "./ImageBackendError.js";
import type { ImageCacheKey } from "./ImageCacheKey.js";
import { ImageFacts } from "./ImageFacts.js";
import { ImageGenerateError } from "./ImageGenerateError.js";

/**
 * Options for {@link ImageCacheShape.getOrGenerate}.
 *
 * @public
 */
export interface GetOrGenerateOptions<F extends Images.ImageFormat = Images.ImageFormat> {
	/**
	 * Formats the caller will use. A stored image outside it is a miss; a generated one outside it fails. The result's
	 * `facts.format` is narrowed to these formats.
	 */
	readonly accept?: ReadonlyArray<F>;
}

/**
 * What {@link ImageCacheShape.getOrGenerate} returns.
 *
 * @public
 */
export interface ImageCacheResult<F extends Images.ImageFormat = Images.ImageFormat> {
	/** The image bytes. */
	readonly bytes: Uint8Array;
	/** The facts read from those bytes, with `format` narrowed to the formats the call accepted. */
	readonly facts: Images.ImageFacts & { readonly format: F };
	/** True when the bytes came from the backend rather than the generator. */
	readonly hit: boolean;
}

/**
 * The image cache service.
 *
 * @public
 */
export interface ImageCacheShape {
	/**
	 * Return the image stored under `key`, or run `generate`, check its output, store it and return it.
	 *
	 * @remarks
	 * Stored bytes are re-read with `ImageFacts`: unreadable bytes, or a format outside `accept`, are a miss and are
	 * overwritten. Generated bytes that are empty, unreadable or outside `accept` fail with `ImageGenerateError` and are
	 * never stored. Backend failures are surfaced, never swallowed. With `accept`, the result's `facts.format` is typed
	 * as the accepted formats; without it, every `ImageFormat`. The two cases are separate overloads so a format type
	 * argument can only be given alongside the `accept` list that enforces it at run time.
	 */
	readonly getOrGenerate: {
		<E, R, const F extends Images.ImageFormat>(
			key: ImageCacheKey,
			generate: () => Effect.Effect<Uint8Array, E, R>,
			options: GetOrGenerateOptions<F> & { readonly accept: ReadonlyArray<F> },
		): Effect.Effect<ImageCacheResult<F>, ImageGenerateError | ImageBackendError | E, R>;
		<E, R>(
			key: ImageCacheKey,
			generate: () => Effect.Effect<Uint8Array, E, R>,
			options?: GetOrGenerateOptions,
		): Effect.Effect<ImageCacheResult, ImageGenerateError | ImageBackendError | E, R>;
	};
}

/**
 * True when `accept` admits the facts' format. With `accept` omitted the call's `F` is every format, so admitting
 * everything is exactly the narrowing the guard claims.
 */
const accepted = <F extends Images.ImageFormat>(
	facts: Images.ImageFacts,
	accept: ReadonlyArray<F> | undefined,
): facts is Images.ImageFacts & { readonly format: F } =>
	accept === undefined || (accept as ReadonlyArray<Images.ImageFormat>).includes(facts.format);

/**
 * A cache for generated images, keyed by `ImageCacheKey`, stored through {@link ImageBackend}.
 *
 * @public
 */
export class ImageCache extends Context.Service<ImageCache, ImageCacheShape>()("@effected/images/ImageCache") {
	/** The cache over whichever {@link ImageBackend} the app provides. */
	static readonly layer: Layer.Layer<ImageCache, never, ImageBackend> = Layer.effect(
		ImageCache,
		Effect.gen(function* () {
			const backend = yield* ImageBackend;
			const getOrGenerate = <E, R, const F extends Images.ImageFormat = Images.ImageFormat>(
				key: ImageCacheKey,
				generate: () => Effect.Effect<Uint8Array, E, R>,
				options?: GetOrGenerateOptions<F>,
			): Effect.Effect<ImageCacheResult<F>, ImageGenerateError | ImageBackendError | E, R> =>
				Effect.gen(function* () {
					const accept = options?.accept;
					const stored = yield* backend.get(key.digest);
					if (Option.isSome(stored)) {
						const facts = ImageFacts.fromBytesResult(stored.value.value);
						if (Result.isSuccess(facts) && accepted(facts.success, accept)) {
							yield* Effect.annotateCurrentSpan({ hit: true, format: facts.success.format });
							return { bytes: stored.value.value, facts: facts.success, hit: true };
						}
					}
					// Annotated as soon as each fact is known, so a miss that fails later still carries it.
					yield* Effect.annotateCurrentSpan("hit", false);
					const bytes = yield* generate();
					if (bytes.byteLength === 0) return yield* new ImageGenerateError({ reason: "empty" });
					const parsed = ImageFacts.fromBytesResult(bytes);
					if (Result.isFailure(parsed)) {
						return yield* new ImageGenerateError({ reason: "unparseable", cause: parsed.failure });
					}
					const facts = parsed.success;
					yield* Effect.annotateCurrentSpan("format", facts.format);
					if (!accepted(facts, accept)) {
						return yield* new ImageGenerateError({
							reason: "rejected-format",
							format: facts.format,
							accept: [...(accept ?? [])],
						});
					}
					yield* backend.set({ key: key.digest, value: bytes, contentType: facts.mimeType, tags: [key.namespace] });
					return { bytes, facts, hit: false };
				}).pipe(Effect.withSpan("ImageCache.getOrGenerate", { attributes: { namespace: key.namespace } }));
			return { getOrGenerate };
		}),
	);
}
