// Root types are named through the package's own name, so the emitted cache.d.ts imports them from "@effected/images".
import type * as Images from "@effected/images";
import { Context, Effect, FileSystem, Layer, Option, Path, Random } from "effect";
import { ImageBackendError } from "./ImageBackendError.js";
import { EXTENSIONS, MIME_TYPES } from "./ImageFormat.js";
import { DIGEST_PATTERN } from "./internal/digest.js";

/**
 * Bytes and media type a backend holds for one key.
 *
 * @public
 */
export interface StoredImage {
	readonly value: Uint8Array;
	readonly contentType: string;
}

/**
 * What {@link ImageBackendShape.set} writes.
 *
 * @public
 */
export interface ImageBackendSetParams {
	readonly key: string;
	readonly value: Uint8Array;
	readonly contentType?: string;
	readonly tags?: ReadonlyArray<string>;
}

/**
 * The port an image cache stores through.
 *
 * @remarks
 * Failures are {@link ImageBackendError}. `@effected/store`'s `Cache` is adapted through
 * `ImageBackend.layerFrom`, which {@link ImageBackendSource} describes structurally.
 *
 * @public
 */
export interface ImageBackendShape {
	readonly get: (key: string) => Effect.Effect<Option.Option<StoredImage>, ImageBackendError>;
	readonly set: (params: ImageBackendSetParams) => Effect.Effect<void, ImageBackendError>;
}

/**
 * Any service whose shape can stand behind the image cache.
 *
 * @remarks
 * `@effected/store`'s `CacheShape` satisfies it: its `get` yields a wider `CacheEntry`, and its `set` accepts these
 * params plus a `ttl`. Failures may be of any type; `ImageBackend.layerFrom` wraps them.
 *
 * @public
 */
export interface ImageBackendSource {
	readonly get: (key: string) => Effect.Effect<Option.Option<StoredImage>, unknown>;
	readonly set: (params: ImageBackendSetParams) => Effect.Effect<void, unknown>;
}

/** `[extension, media type]` pairs, in the fixed order `get` probes them, from the package's one extension table. */
const FILES = Object.entries(EXTENSIONS).map(
	([format, ext]) => [ext, MIME_TYPES[format as Images.ImageFormat]] as const,
);
/** Media type to extension. Read only through `Object.hasOwn`: a content type is caller input. */
const EXTENSION_BY_TYPE: Readonly<Record<string, string>> = Object.fromEntries(FILES.map(([ext, type]) => [type, ext]));

const assertDigest = (key: string): Effect.Effect<void> =>
	DIGEST_PATTERN.test(key)
		? Effect.void
		: Effect.die(new TypeError(`image backend key ${JSON.stringify(key)} is not a 64-char hex digest`));

/**
 * The storage port behind `ImageCache`.
 *
 * @public
 */
export class ImageBackend extends Context.Service<ImageBackend, ImageBackendShape>()("@effected/images/ImageBackend") {
	/**
	 * The backend that stores nothing: `get` always misses and `set` discards the bytes.
	 *
	 * @remarks
	 * "The cache is off" as a layer, so a program keeps one `ImageCache.getOrGenerate` code path whether caching is
	 * enabled or not: provide this when it is off and `layerDirectory` (or `layerFrom`) when it is on. Every call runs
	 * the generator and returns `hit: false`; the generated bytes are still read and checked against `accept`. It needs
	 * nothing in `R`, never fails, and is a plain value, so it builds once however often it is provided.
	 */
	static readonly layerNone: Layer.Layer<ImageBackend> = Layer.succeed(this)({
		get: () => Effect.succeedNone,
		set: () => Effect.void,
	});

	/**
	 * A backend over one directory: `<directory>/<key>.<ext>`.
	 *
	 * @remarks
	 * Writes go to a temp file in the same directory and are renamed into place, so a failed or interrupted write
	 * never leaves a file that reads as a hit. Tags are accepted and ignored — a directory has no tag index. Keys must
	 * be 64-char lowercase hex digests (as `ImageCacheKey` produces); anything else is a defect, so a key can never
	 * name a path outside the directory. No expiry or eviction.
	 *
	 * Each call mints a fresh layer; bind the result to a `const` or the backend builds twice.
	 */
	static layerDirectory(options: {
		readonly directory: string;
	}): Layer.Layer<ImageBackend, never, FileSystem.FileSystem | Path.Path> {
		return Layer.effect(
			ImageBackend,
			Effect.gen(function* () {
				const fs = yield* FileSystem.FileSystem;
				const path = yield* Path.Path;
				const fileFor = (key: string, ext: string) => path.join(options.directory, `${key}.${ext}`);

				const get = Effect.fn("ImageBackend.get")(function* (key: string) {
					yield* assertDigest(key);
					for (const [ext, contentType] of FILES) {
						const bytes = yield* fs.readFile(fileFor(key, ext)).pipe(
							Effect.map(Option.some),
							Effect.catchReason("PlatformError", "NotFound", () => Effect.succeedNone),
							Effect.mapError((cause) => new ImageBackendError({ operation: "get", key, cause })),
						);
						if (Option.isSome(bytes)) return Option.some<StoredImage>({ value: bytes.value, contentType });
					}
					return Option.none<StoredImage>();
				});

				const set = Effect.fn("ImageBackend.set")(function* (params: ImageBackendSetParams) {
					yield* assertDigest(params.key);
					const ext =
						params.contentType !== undefined && Object.hasOwn(EXTENSION_BY_TYPE, params.contentType)
							? EXTENSION_BY_TYPE[params.contentType]
							: undefined;
					if (ext === undefined) {
						return yield* new ImageBackendError({
							operation: "set",
							key: params.key,
							cause: new Error(`unsupported content type ${JSON.stringify(params.contentType ?? null)}`),
						});
					}
					const target = fileFor(params.key, ext);
					const suffix = yield* Random.nextIntBetween(0, 0x7fffffff);
					const temp = path.join(options.directory, `.${params.key}.${suffix.toString(36)}.tmp`);
					// Stale other-format files are removed BEFORE the rename. Removing them after would let two concurrent
					// writers of different formats each delete the other's freshly renamed file, leaving no hit at all.
					// Removing first can at worst leave two complete files, and get's fixed extension order picks one.
					const write = Effect.gen(function* () {
						yield* fs.makeDirectory(options.directory, { recursive: true });
						yield* fs.writeFile(temp, params.value);
						for (const [other] of FILES) {
							if (other !== ext) yield* fs.remove(fileFor(params.key, other), { force: true });
						}
						yield* fs.rename(temp, target);
					});
					yield* write.pipe(
						Effect.onError(() => fs.remove(temp, { force: true }).pipe(Effect.ignore)),
						Effect.mapError((cause) => new ImageBackendError({ operation: "set", key: params.key, cause })),
					);
				});

				return { get, set };
			}),
		);
	}

	/**
	 * Adapt any structurally matching service, `@effected/store`'s `Cache` being the intended one, as the backend.
	 *
	 * @remarks
	 * `ImageBackend.layerFrom(Cache)` gives the image cache store's TTL, eviction and tag invalidation. Every source
	 * failure is wrapped as {@link ImageBackendError} with the original as `cause`.
	 *
	 * Each call mints a fresh layer; bind the result to a `const` or the backend builds twice.
	 */
	static layerFrom<I>(key: Context.Key<I, ImageBackendSource>): Layer.Layer<ImageBackend, never, I> {
		return Layer.effect(
			ImageBackend,
			Effect.map(key, (source) => ({
				get: (k: string) =>
					source.get(k).pipe(
						Effect.map(Option.map((entry) => ({ value: entry.value, contentType: entry.contentType }))),
						Effect.mapError((cause) => new ImageBackendError({ operation: "get", key: k, cause })),
						Effect.withSpan("ImageBackend.get"),
					),
				set: (params: ImageBackendSetParams) =>
					source.set(params).pipe(
						Effect.mapError((cause) => new ImageBackendError({ operation: "set", key: params.key, cause })),
						Effect.withSpan("ImageBackend.set"),
					),
			})),
		);
	}
}
