// The hostility suite: malformed and adversarial input must exit through the
// typed LockfileParseError — correct stage, never a defect, never prototype
// pollution, never a stack overflow. The text-parsing engines are delegated
// (@effected/yaml, @effected/jsonc, native JSON.parse), so these tests prove
// the delegated typed failures actually surface through Lockfile.parse.

import { assert, describe, it } from "@effect/vitest";
import { Effect, Option } from "effect";
import { Lockfile, LockfileParseError } from "../src/Lockfile.js";
import type { LockfileFormat } from "../src/LockfileFormat.js";

/** Flip a failing parse and hand back the typed error. */
const parseError = (content: string, format: LockfileFormat) =>
	Effect.gen(function* () {
		const error = yield* Effect.flip(Lockfile.parse(content, { format }));
		assert.instanceOf(error, LockfileParseError);
		assert.strictEqual(error.format, format);
		return error;
	});

/** Prove Object.prototype picked up nothing from a hostile parse. */
const assertPrototypeUnpolluted = (): void => {
	assert.strictEqual(({} as Record<string, unknown>).polluted, undefined);
	assert.isFalse(Object.hasOwn(Object.prototype, "polluted"));
};

describe("hostile input", () => {
	describe("malformed text fails at stage 'syntax'", () => {
		it.effect("pnpm: broken YAML", () =>
			Effect.gen(function* () {
				const error = yield* parseError("importers:\n  - [unclosed\n\tflow", "pnpm");
				assert.strictEqual(error.stage, "syntax");
			}),
		);

		it.effect("yarn: broken YAML", () =>
			Effect.gen(function* () {
				const error = yield* parseError('"a@npm:^1":\n  version: "1\n', "yarn");
				assert.strictEqual(error.stage, "syntax");
			}),
		);

		it.effect("npm: broken JSON", () =>
			Effect.gen(function* () {
				const error = yield* parseError("{ definitely not json", "npm");
				assert.strictEqual(error.stage, "syntax");
			}),
		);

		it.effect("bun: broken JSONC", () =>
			Effect.gen(function* () {
				const error = yield* parseError('{ "lockfileVersion": 1, /* unclosed comment', "bun");
				assert.strictEqual(error.stage, "syntax");
			}),
		);
	});

	describe("well-formed text with the wrong shape fails at stage 'validation'", () => {
		it.effect("pnpm: missing importers", () =>
			Effect.gen(function* () {
				const error = yield* parseError("lockfileVersion: '9.0'\n", "pnpm");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("pnpm: importers of the wrong type", () =>
			Effect.gen(function* () {
				const error = yield* parseError("lockfileVersion: '9.0'\nimporters: 42\n", "pnpm");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("npm: missing lockfileVersion", () =>
			Effect.gen(function* () {
				const error = yield* parseError("{}", "npm");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("npm: a top-level array", () =>
			Effect.gen(function* () {
				const error = yield* parseError("[1, 2, 3]", "npm");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("yarn: a top-level scalar", () =>
			Effect.gen(function* () {
				const error = yield* parseError("42\n", "yarn");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("yarn: an entry of the wrong type", () =>
			Effect.gen(function* () {
				const error = yield* parseError('"a@npm:^1.0.0": 42\n', "yarn");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("bun: missing lockfileVersion", () =>
			Effect.gen(function* () {
				const error = yield* parseError("{}", "bun");
				assert.strictEqual(error.stage, "validation");
			}),
		);
	});

	describe("yarn classic (v1) content is rejected, never mis-normalized", () => {
		// Classic yarn.lock is not YAML. This particular content happens to
		// YAML-parse (each entry body reads as a multi-line plain scalar), so it
		// must die at entry validation — Berry-only support is scope honesty.
		const classic = [
			"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
			"# yarn lockfile v1",
			"",
			"",
			"lodash@^4.17.21:",
			'  version "4.17.21"',
			'  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"',
			"  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==",
			"",
		].join("\n");

		it.effect("fails typed with format 'yarn'", () =>
			Effect.gen(function* () {
				const error = yield* parseError(classic, "yarn");
				assert.strictEqual(error.stage, "validation");
			}),
		);
	});

	describe("prototype-pollution discipline", () => {
		it.effect("a __proto__ pnpm importer neither pollutes nor crashes", () =>
			Effect.gen(function* () {
				const content = [
					"lockfileVersion: '9.0'",
					"importers:",
					"  __proto__:",
					"    dependencies:",
					"      polluted:",
					"        specifier: '1.0.0'",
					"        version: 1.0.0",
					"  constructor:",
					"    devDependencies:",
					"      polluted:",
					"        specifier: '1.0.0'",
					"        version: 1.0.0",
				].join("\n");
				const lockfile = yield* Lockfile.parse(content, { format: "pnpm" });
				assertPrototypeUnpolluted();
				// The hostile importer names are honest data, held in Map-backed
				// intermediates and schema-decoded records.
				assert.deepStrictEqual(lockfile.workspacePackages.map((p) => p.name).sort(), ["__proto__", "constructor"]);
			}),
		);

		it.effect("__proto__ npm package keys and dependency maps neither pollute nor crash", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 3,
					packages: {
						"": { name: "root" },
						"node_modules/__proto__": {
							version: "1.0.0",
							// A literal `__proto__:` key is special syntax the literal would
							// swallow — build the own property for real so the hostile key
							// actually reaches the serialized lockfile.
							dependencies: Object.fromEntries([
								["__proto__", "1.0.0"],
								["constructor", "2.0.0"],
							]),
						},
						"node_modules/constructor": { version: "1.0.0" },
					},
				});
				assert.include(content, '"__proto__":"1.0.0"'); // the hostile key survived serialization
				const lockfile = yield* Lockfile.parse(content, { format: "npm" });
				assertPrototypeUnpolluted();
				assert.strictEqual(lockfile.packagesNamed("__proto__").length, 1);
				assert.strictEqual(lockfile.packagesNamed("constructor").length, 1);
				const evil = lockfile.packagesNamed("__proto__")[0];
				const protoEntry = Object.entries(evil?.dependencies ?? {}).find(([k]) => k === "__proto__");
				assert.deepStrictEqual(protoEntry, ["__proto__", "1.0.0"]); // own enumerable property, not dropped
			}),
		);

		it.effect("a __proto__ importer path and dependency name populate importers without polluting", () =>
			Effect.gen(function* () {
				const content = [
					"lockfileVersion: '9.0'",
					"importers:",
					"  __proto__:",
					"    dependencies:",
					"      __proto__:",
					"        specifier: '1.0.0'",
					"        version: 1.0.0",
					"  .: {}",
				].join("\n");
				const lockfile = yield* Lockfile.parse(content, { format: "pnpm" });
				assertPrototypeUnpolluted();

				// The importer index is Map-backed, so a hostile path is honest data,
				// not a prototype write.
				const evil = Option.getOrThrow(lockfile.importer("__proto__"));
				assert.strictEqual(evil.path, "__proto__");
				const dep = evil.dependencies.find((d) => d.name === "__proto__");
				assert.strictEqual(dep?.specifier.raw, "1.0.0");
				assert.strictEqual(dep?.specifier._tag, "range");

				assert.isTrue(Option.isSome(lockfile.importer(".")));
			}),
		);

		it.effect("a __proto__ bun workspace neither pollutes nor crashes", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 1,
					workspaces: {
						"": { name: "root" },
						"packages/evil": { name: "__proto__", version: "1.0.0" },
					},
				});
				const lockfile = yield* Lockfile.parse(content, { format: "bun" });
				assertPrototypeUnpolluted();
				assert.strictEqual(lockfile.workspacePackages[0]?.name, "__proto__");
			}),
		);
	});

	describe("hostile name@version keys are skipped, never thrown on", () => {
		it.effect("pnpm: '@', '@scope/', bare and empty keys", () =>
			Effect.gen(function* () {
				const content = [
					"lockfileVersion: '9.0'",
					"importers:",
					"  .: {}",
					"packages:",
					"  '@': {}",
					"  '@scope/': {}",
					"  bare-no-at: {}",
					"  'ok@1.0.0': {}",
				].join("\n");
				const lockfile = yield* Lockfile.parse(content, { format: "pnpm" });
				// Only the well-formed key survives.
				assert.deepStrictEqual(
					lockfile.packages.map((p) => [p.name, p.version]),
					[["ok", "1.0.0"]],
				);
			}),
		);

		it.effect("bun: malformed and non-string package tuples", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 1,
					packages: {
						a: [], // empty tuple
						b: [42], // non-string id
						c: ["@"], // lone @
						d: ["@scope/"], // trailing slash, no version
						e: ["no-at-sign"],
						f: ["ok@1.0.0", "", {}, "sha512-abc"],
					},
				});
				const lockfile = yield* Lockfile.parse(content, { format: "bun" });
				assert.deepStrictEqual(
					lockfile.packages.map((p) => [p.name, p.version, p.integrity]),
					[["ok", "1.0.0", "sha512-abc"]],
				);
			}),
		);

		it.effect("yarn: descriptors without an extractable name", () =>
			Effect.gen(function* () {
				const content = [
					"__metadata:",
					"  version: 8",
					'"@npm:^1.0.0": {}', // name would be empty
					'"no-descriptor-at-all": {}',
					'"ok@npm:^1.0.0":',
					'  version: "1.2.3"',
				].join("\n");
				const lockfile = yield* Lockfile.parse(content, { format: "yarn" });
				assert.deepStrictEqual(
					lockfile.packages.map((p) => [p.name, p.version]),
					[["ok", "1.2.3"]],
				);
			}),
		);
	});

	describe("a present but unparseable integrity fails typed at stage 'validation'", () => {
		// yarn's `10c0/<hex>`, npm/pnpm SRI and corepack forms all validate as an
		// `IntegrityHash`, so real fixtures parse green (proved by the fixture
		// corpus). Only a genuinely-corrupt *present* integrity fails here; an
		// *absent* integrity is still omitted and the parse succeeds.
		const CORRUPT = "not-a-valid-integrity";

		it.effect("npm: a corrupt package integrity", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 3,
					packages: {
						"": { name: "root" },
						"node_modules/foo": { version: "1.0.0", integrity: CORRUPT },
					},
				});
				const error = yield* parseError(content, "npm");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("pnpm: a corrupt package resolution integrity", () =>
			Effect.gen(function* () {
				const content = [
					"lockfileVersion: '9.0'",
					"importers:",
					"  .: {}",
					"packages:",
					"  'foo@1.0.0':",
					"    resolution:",
					`      integrity: ${CORRUPT}`,
				].join("\n");
				const error = yield* parseError(content, "pnpm");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("yarn: a corrupt entry checksum", () =>
			Effect.gen(function* () {
				const content = [
					"__metadata:",
					"  version: 8",
					'"ok@npm:^1.0.0":',
					'  version: "1.2.3"',
					`  checksum: ${CORRUPT}`,
				].join("\n");
				const error = yield* parseError(content, "yarn");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("bun: a corrupt package-tuple integrity", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 1,
					packages: { foo: ["foo@1.0.0", "", {}, CORRUPT] },
				});
				const error = yield* parseError(content, "bun");
				assert.strictEqual(error.stage, "validation");
			}),
		);

		it.effect("an absent integrity is omitted and the parse succeeds", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 3,
					packages: {
						"": { name: "root" },
						"node_modules/foo": { version: "1.0.0" },
					},
				});
				const lockfile = yield* Lockfile.parse(content, { format: "npm" });
				const foo = lockfile.packagesNamed("foo")[0];
				assert.strictEqual(foo?.integrity, undefined);
			}),
		);
	});

	describe("empty importer paths are skipped, never thrown on", () => {
		// `LockfileImporter.path` is a `NonEmptyString`, so an empty importer path
		// would die as a defect at construction. The parsers skip such rows before
		// construction — the same total-skip discipline as malformed name keys.
		it.effect("npm: a link entry with an empty resolved path is skipped, parse succeeds", () =>
			Effect.gen(function* () {
				const content = JSON.stringify({
					lockfileVersion: 3,
					packages: {
						"": { name: "root" },
						"node_modules/pkg": { link: true, resolved: "" },
					},
				});
				const lockfile = yield* Lockfile.parse(content, { format: "npm" });
				// The empty-path importer is not represented; the "." root importer is.
				assert.isTrue(Option.isNone(lockfile.importer("")));
				assert.isTrue(Option.isSome(lockfile.importer(".")));
			}),
		);

		it.effect("pnpm: an empty importer key is skipped, parse succeeds", () =>
			Effect.gen(function* () {
				const content = ["lockfileVersion: '9.0'", "importers:", "  '': {}", "  .: {}"].join("\n");
				const lockfile = yield* Lockfile.parse(content, { format: "pnpm" });
				assert.isTrue(Option.isNone(lockfile.importer("")));
				assert.isTrue(Option.isSome(lockfile.importer(".")));
			}),
		);
	});

	describe("deep-nesting bombs surface the delegated engines' typed failures", () => {
		it.effect("npm: a deeply nested JSON document fails typed, never a defect", () =>
			Effect.gen(function* () {
				const depth = 200_000;
				const content = "[".repeat(depth) + "]".repeat(depth);
				const error = yield* parseError(content, "npm");
				// Whether V8 throws RangeError (depth) or the shape check rejects a
				// top-level array, the failure is typed.
				assert.isTrue(error.stage === "syntax" || error.stage === "validation");
			}),
		);

		it.effect("pnpm: a YAML flow-nesting bomb fails typed", () =>
			Effect.gen(function* () {
				const error = yield* parseError(`importers: ${"[".repeat(10_000)}`, "pnpm");
				assert.strictEqual(error.stage, "syntax");
			}),
		);

		it.effect("yarn: a YAML flow-nesting bomb fails typed", () =>
			Effect.gen(function* () {
				const error = yield* parseError(`entry: ${"{a: ".repeat(10_000)}`, "yarn");
				assert.strictEqual(error.stage, "syntax");
			}),
		);

		it.effect("bun: a JSONC nesting bomb fails typed", () =>
			Effect.gen(function* () {
				const content = `{"lockfileVersion": 1, "packages": ${"[".repeat(10_000)}`;
				const error = yield* parseError(content, "bun");
				assert.strictEqual(error.stage, "syntax");
			}),
		);
	});

	describe("error surface", () => {
		it.effect("LockfileParseError message names the format and stage", () =>
			Effect.gen(function* () {
				const error = yield* parseError("{ nope", "npm");
				assert.strictEqual(error._tag, "LockfileParseError");
				assert.include(error.message, "npm");
				assert.include(error.message, "not well-formed");
			}),
		);

		it.effect("the underlying cause is preserved structurally, not stringified", () =>
			Effect.gen(function* () {
				const error = yield* parseError("{ nope", "npm");
				assert.instanceOf(error.cause, SyntaxError);
			}),
		);
	});
});
