// Regenerates the peerDependencyRules.allowedVersions block in savvy.build.ts.
//
// Why a rewrite script instead of computing the table inside the config:
// `rolldown-pnpm-config export` statically evaluates the PnpmConfigPlugin
// argument from SOURCE and hard-fails on any non-literal value (getter, call,
// spread), so the exported table must exist as pure literals in the file. This
// script derives those literals from the same file's own `catalogs` literal —
// the single source of truth `pnpm:up` maintains — and splices them between
// sentinel comments, so the table can never drift from the catalog it mirrors.
//
// The rules are version-qualified parent selectors over the effect satellite
// family — one `"<satellite>@<its pin>>effect"` rule per v4 lock-catalog
// package, valued at the effect pin — never blanket and never name-only: the
// same satellite names ship on the Effect v3 line (the effect3 interop
// catalogs), and pnpm's matcher applies a qualified rule only when the actual
// parent instance's version satisfies the qualifier (verified in pnpm
// 11.15.0: `parsePkgAndParentSelector` parses `name@version>peer`, and the
// bad-issue filter checks `semver.satisfies(parentVersion, qualifier)`), so a
// v3 satellite's genuine unmet `^3` peer still warns. The @effected kit's own
// published artifacts are deliberately NOT covered: those strand only until
// the toolchain republish cycle catches up, which is accepted — the table
// exists for the uncontrollable drift class, effect's own satellites sitting
// at a different beta than the installed effect.
//
// Invoked by this package's `pnpm:export` script ahead of the real export;
// runnable directly with `node allowed-versions.gen.ts`. Tests import the
// exported functions; the write only happens under `import.meta.main`.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Sentinel opening the generated block (whole line, tab-indented). */
export const BLOCK_START =
	"\t\t\t// generated by allowed-versions.gen.ts — run pnpm pnpm:export to refresh; do not edit by hand";

/** Sentinel closing the generated block (whole line, tab-indented). */
export const BLOCK_END = "\t\t\t// end generated allowed-versions";

/** An exact version: no range operator, no wildcard — `X.Y.Z` with an optional prerelease. */
const EXACT_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

/** A v4 lock-catalog entry: the package and its pinned range. */
export interface LockEntry {
	readonly name: string;
	readonly range: string;
}

/**
 * Pull every `strategy: "lock"` catalog entry out of the config source — the
 * v4 catalog's membership (the `effect3` catalog is all `interop`, so the
 * strategy is what disambiguates). Keys are quoted (`"@effect/x"`) except the
 * bare `effect` identifier; both forms are matched.
 */
export const extractLockEntries = (source: string): ReadonlyArray<LockEntry> => {
	const entries: Array<LockEntry> = [];
	for (const match of source.matchAll(
		/\n\t{6}(?:"([^"]+)"|([A-Za-z_$][\w$]*)):\s*\{\s*\n\t{7}range:\s*"([^"]+)",\s*\n\t{7}peer:\s*"[^"]+",\s*\n\t{7}strategy:\s*"lock"/g,
	)) {
		entries.push({ name: match[1] ?? match[2] ?? "", range: match[3] ?? "" });
	}
	return entries;
};

/**
 * The version-qualified rule table: one `"<satellite>@<its pin>>effect"` rule
 * per lock-catalog package, valued at the effect pin. The bare `effect` entry
 * supplies the value and gets no rule of its own (it cannot be its own peer
 * parent); entries whose range is not an exact version are skipped — a range
 * cannot qualify a parent instance exactly, and widening would recreate the
 * masking risk. A missing or non-exact effect pin is a hard error.
 */
export const deriveAllowedVersions = (entries: ReadonlyArray<LockEntry>): Record<string, string> => {
	const effectEntry = entries.find((entry) => entry.name === "effect");
	if (effectEntry === undefined || !EXACT_VERSION.test(effectEntry.range)) {
		throw new Error(`the effect lock pin is missing or not exact: ${JSON.stringify(effectEntry?.range)}`);
	}
	const table: Record<string, string> = {};
	for (const { name, range } of entries) {
		if (name === "effect" || !EXACT_VERSION.test(range)) continue;
		table[`${name}@${range}>effect`] = effectEntry.range;
	}
	return table;
};

/** Render the sentinel-wrapped literal block, biome-style (tabs, double quotes, trailing commas). */
export const renderBlock = (table: Record<string, string>): string => {
	const entries = Object.keys(table)
		.sort()
		.map((key) => `\t\t\t\t\t${JSON.stringify(key)}: ${JSON.stringify(table[key])},`)
		.join("\n");
	return [
		BLOCK_START,
		"\t\t\tpeerDependencyRules: {",
		"\t\t\t\tallowedVersions: {",
		entries,
		"\t\t\t\t},",
		"\t\t\t},",
		BLOCK_END,
	].join("\n");
};

/**
 * Replace the existing sentinel-wrapped block, or insert one after the plugin's
 * `name:` line when absent. Idempotent: splicing an already-current source
 * returns it unchanged.
 */
export const spliceBlock = (source: string, rendered: string): string => {
	const start = source.indexOf(BLOCK_START);
	const end = source.indexOf(BLOCK_END);
	if (start !== -1 || end !== -1) {
		if (start === -1 || end === -1 || end < start) {
			throw new Error("malformed generated block: sentinels missing or out of order");
		}
		return source.slice(0, start) + rendered + source.slice(end + BLOCK_END.length);
	}
	const anchor = source.match(/\n\t{3}name: "@effected\/pnpm-plugin-effect",\n/);
	if (anchor?.index === undefined) {
		throw new Error("cannot find the plugin name anchor to insert the generated block");
	}
	const insertAt = anchor.index + anchor[0].length;
	return `${source.slice(0, insertAt)}${rendered}\n${source.slice(insertAt)}`;
};

/** Derive the current table from the config source alone. */
export const regenerate = (source: string): string =>
	spliceBlock(source, renderBlock(deriveAllowedVersions(extractLockEntries(source))));

if (import.meta.main) {
	const here = dirname(fileURLToPath(import.meta.url));
	const configFile = join(here, "savvy.build.ts");
	const before = readFileSync(configFile, "utf8");
	const after = regenerate(before);
	if (after === before) {
		console.log("allowed-versions: table already current");
	} else {
		writeFileSync(configFile, after);
		console.log("allowed-versions: table regenerated");
	}
}
