// Regenerates the peerDependencyRules.allowedVersions block in savvy.build.ts.
//
// Why a rewrite script instead of computing the table inside the config:
// `rolldown-pnpm-config export` statically evaluates the PnpmConfigPlugin
// argument from SOURCE and hard-fails on any non-literal value (getter, call,
// spread), so the exported table must exist as pure literals in the file. This
// script derives those literals from the same file's own `catalogs` literal —
// the single source of truth `pnpm:up` maintains — and splices them between
// sentinel comments, so the table can never drift from the catalog it mirrors.
//
// The rules are parent-scoped ("<member>>effect"), never blanket: a blanket
// `effect` rule would also silence a genuine Effect v3 satellite's unmet `^3`
// peer, because pnpm checks the found version against the rule range
// regardless of what the parent asked for. One rule per @effected workspace
// member; rules for parents absent from the installed graph never match and
// are harmless. Values are the lock catalog's exact beta only.
//
// Invoked by this package's `pnpm:export` script ahead of the real export;
// runnable directly with `node allowed-versions.gen.ts`. Tests import the
// exported functions; the write only happens under `import.meta.main`.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Sentinel opening the generated block (whole line, tab-indented). */
export const BLOCK_START =
	"\t\t\t// generated by allowed-versions.gen.ts — run pnpm pnpm:export to refresh; do not edit by hand";

/** Sentinel closing the generated block (whole line, tab-indented). */
export const BLOCK_END = "\t\t\t// end generated allowed-versions";

/** An exact version: no range operator, no wildcard — `X.Y.Z` with an optional prerelease. */
const EXACT_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

/**
 * Pull the effect lock catalog's pinned beta out of the config source: the
 * bare `effect:` package entry whose `strategy` is `"lock"` — the v4 catalog's
 * pin. The `effect3` interop catalog carries a bare `effect:` entry too, so
 * the strategy is what disambiguates, and the scan refuses anything that is
 * not an exact version — exactness is load-bearing for the whole table.
 */
export const extractEffectBeta = (source: string): string => {
	const matches = [
		...source.matchAll(
			/\n\t{6}effect:\s*\{\s*\n\t{7}range:\s*"([^"]+)",\s*\n\t{7}peer:\s*"[^"]+",\s*\n\t{7}strategy:\s*"lock"/g,
		),
	];
	if (matches.length !== 1) {
		throw new Error(`expected exactly one bare effect catalog entry, found ${matches.length}`);
	}
	const version = matches[0]?.[1] ?? "";
	if (!EXACT_VERSION.test(version)) {
		throw new Error(`effect catalog range ${JSON.stringify(version)} is not an exact version`);
	}
	return version;
};

/** The @effected workspace member names, read from packages/<dir>/package.json, sorted. */
export const readMemberNames = (packagesDir: string): ReadonlyArray<string> => {
	const names: Array<string> = [];
	for (const entry of readdirSync(packagesDir, { withFileTypes: true })) {
		if (!entry.isDirectory()) continue;
		let manifest: { name?: unknown };
		try {
			manifest = JSON.parse(readFileSync(join(packagesDir, entry.name, "package.json"), "utf8")) as {
				name?: unknown;
			};
		} catch {
			continue;
		}
		if (typeof manifest.name === "string" && manifest.name.startsWith("@effected/")) {
			names.push(manifest.name);
		}
	}
	return names.sort();
};

/** One parent-scoped rule per member, valued at the exact beta. Never a blanket key. */
export const deriveAllowedVersions = (beta: string, members: ReadonlyArray<string>): Record<string, string> => {
	if (!EXACT_VERSION.test(beta)) {
		throw new Error(`refusing a non-exact beta ${JSON.stringify(beta)}`);
	}
	const table: Record<string, string> = {};
	for (const member of [...members].sort()) {
		if (!member.startsWith("@effected/")) {
			throw new Error(`refusing a non-kit parent ${JSON.stringify(member)}`);
		}
		table[`${member}>effect`] = beta;
	}
	return table;
};

/** Render the sentinel-wrapped literal block, biome-style (tabs, double quotes, trailing commas). */
export const renderBlock = (table: Record<string, string>): string => {
	const entries = Object.keys(table)
		.sort()
		.map((key) => `\t\t\t\t\t${JSON.stringify(key)}: ${JSON.stringify(table[key])},`)
		.join("\n");
	return [
		BLOCK_START,
		"\t\t\tpeerDependencyRules: {",
		"\t\t\t\tallowedVersions: {",
		entries,
		"\t\t\t\t},",
		"\t\t\t},",
		BLOCK_END,
	].join("\n");
};

/**
 * Replace the existing sentinel-wrapped block, or insert one after the plugin's
 * `name:` line when absent. Idempotent: splicing an already-current source
 * returns it unchanged.
 */
export const spliceBlock = (source: string, rendered: string): string => {
	const start = source.indexOf(BLOCK_START);
	const end = source.indexOf(BLOCK_END);
	if (start !== -1 || end !== -1) {
		if (start === -1 || end === -1 || end < start) {
			throw new Error("malformed generated block: sentinels missing or out of order");
		}
		return source.slice(0, start) + rendered + source.slice(end + BLOCK_END.length);
	}
	const anchor = source.match(/\n\t{3}name: "@effected\/pnpm-plugin-effect",\n/);
	if (anchor?.index === undefined) {
		throw new Error("cannot find the plugin name anchor to insert the generated block");
	}
	const insertAt = anchor.index + anchor[0].length;
	return `${source.slice(0, insertAt)}${rendered}\n${source.slice(insertAt)}`;
};

/** Derive the current table for a repo layout: config source + packages dir. */
export const regenerate = (source: string, packagesDir: string): string =>
	spliceBlock(source, renderBlock(deriveAllowedVersions(extractEffectBeta(source), readMemberNames(packagesDir))));

if (import.meta.main) {
	const here = dirname(fileURLToPath(import.meta.url));
	const configFile = join(here, "savvy.build.ts");
	const packagesDir = dirname(here);
	const before = readFileSync(configFile, "utf8");
	const after = regenerate(before, packagesDir);
	if (after === before) {
		console.log("allowed-versions: table already current");
	} else {
		writeFileSync(configFile, after);
		console.log("allowed-versions: table regenerated");
	}
}
