// Vendored SPDX license exception identifier lists. The two arrays below are
// machine-generated by `scripts/generate-data.ts` from the `spdx-exceptions`
// package (https://github.com/kemitchell/spdx-exceptions.json), CC-BY-3.0.
// That package republishes the SPDX exceptions list maintained by the Linux
// Foundation's SPDX workgroup (https://spdx.org/licenses/exceptions-index.html).
// Do not edit the arrays by hand — run the generator to refresh them, which
// rewrites only the byte span between each pair of markers.

/** @internal */
export const ACTIVE_EXCEPTION_IDS = [
	// spdx:exceptions:active:start
	"389-exception",
	"Asterisk-exception",
	"Autoconf-exception-2.0",
	"Autoconf-exception-3.0",
	"Autoconf-exception-generic",
	"Autoconf-exception-generic-3.0",
	"Autoconf-exception-macro",
	"Bison-exception-1.24",
	"Bison-exception-2.2",
	"Bootloader-exception",
	"CLISP-exception-2.0",
	"Classpath-exception-2.0",
	"DigiRule-FOSS-exception",
	"FLTK-exception",
	"Fawkes-Runtime-exception",
	"Font-exception-2.0",
	"GCC-exception-2.0",
	"GCC-exception-2.0-note",
	"GCC-exception-3.1",
	"GNAT-exception",
	"GNOME-examples-exception",
	"GNU-compiler-exception",
	"GPL-3.0-interface-exception",
	"GPL-3.0-linking-exception",
	"GPL-3.0-linking-source-exception",
	"GPL-CC-1.0",
	"GStreamer-exception-2005",
	"GStreamer-exception-2008",
	"Gmsh-exception",
	"KiCad-libraries-exception",
	"LGPL-3.0-linking-exception",
	"LLGPL",
	"LLVM-exception",
	"LZMA-exception",
	"Libtool-exception",
	"Linux-syscall-note",
	"OCCT-exception-1.0",
	"OCaml-LGPL-linking-exception",
	"OpenJDK-assembly-exception-1.0",
	"PS-or-PDF-font-exception-20170817",
	"QPL-1.0-INRIA-2004-exception",
	"Qt-GPL-exception-1.0",
	"Qt-LGPL-exception-1.1",
	"Qwt-exception-1.0",
	"SANE-exception",
	"SHL-2.0",
	"SHL-2.1",
	"SWI-exception",
	"Swift-exception",
	"Texinfo-exception",
	"UBDL-exception",
	"Universal-FOSS-exception-1.0",
	"WxWindows-exception-3.1",
	"cryptsetup-OpenSSL-exception",
	"eCos-exception-2.0",
	"fmt-exception",
	"freertos-exception-2.0",
	"gnu-javamail-exception",
	"i2p-gpl-java-exception",
	"libpri-OpenH323-exception",
	"mif-exception",
	"openvpn-openssl-exception",
	"stunnel-exception",
	"u-boot-exception-2.0",
	"vsftpd-openssl-exception",
	"x11vnc-openssl-exception",
	// spdx:exceptions:active:end
] as const;

/** @internal */
export const DEPRECATED_EXCEPTION_ID_LIST = [
	// spdx:exceptions:deprecated:start
	"Nokia-Qt-exception-1.1",
	// spdx:exceptions:deprecated:end
] as const;

/** @internal */
export const EXCEPTION_IDS: ReadonlySet<string> = new Set(ACTIVE_EXCEPTION_IDS);

/** @internal */
export const DEPRECATED_EXCEPTION_IDS: ReadonlySet<string> = new Set(DEPRECATED_EXCEPTION_ID_LIST);
