// Vendored SPDX license metadata. The entry array below is machine-generated
// by `scripts/generate-data.ts` from the SPDX workgroup's own published
// catalog, vendored read-only at `.repos/spdx-license-list-data`
// (https://github.com/spdx/license-list-data), CC0-1.0, which republishes the
// SPDX License List (https://spdx.org/licenses/). Do not edit the array by
// hand — run the generator to refresh it, which rewrites only the byte span
// between the markers.
//
// The entries are tuples rather than objects: `[id, name, flags]`, with the
// same 721 ids the `licenseIds.ts` catalog carries. Repeating three object
// keys 721 times would cost consumers roughly 20KB of shipped bytes for no
// information. `reference` is deliberately NOT vendored — every upstream
// entry's URL is exactly `https://spdx.org/licenses/<id>.html`, so it is
// templated in `License.referenceUrl`; the generator asserts that template
// against upstream for every id and fails loudly on any deviation, which
// keeps the templating a checked invariant rather than an assumption.

/** Bit set in a metadata entry's `flags` when the license is OSI-approved. @internal */
export const META_FLAG_OSI_APPROVED = 1;

/** Bit set in a metadata entry's `flags` when the license is FSF-libre. @internal */
export const META_FLAG_FSF_LIBRE = 2;

/**
 * One vendored metadata entry: the SPDX identifier, its full title, and the
 * approval bitfield ({@link META_FLAG_OSI_APPROVED} | {@link META_FLAG_FSF_LIBRE}).
 *
 * @internal
 */
export type LicenseMetaEntry = readonly [id: string, name: string, flags: number];

/**
 * One row per license, TAB-separated as `id\tname\tflags`.
 *
 * @remarks
 * A row is a single string rather than a tuple because **a formatter cannot
 * break a string literal.** The longest SPDX name is 88 characters, which
 * overflows the 120-column limit once the id and flags are appended, so a
 * tuple form gets re-wrapped by Biome — and the generator then rewrites it
 * back. Neither shape is a fixpoint and regeneration reports a spurious diff
 * forever. TAB cannot occur in an SPDX name, so the split is unambiguous.
 *
 * @internal
 */
export const LICENSE_META_ROWS: readonly string[] = [
	// spdx:license-meta:start
	"0BSD\tBSD Zero Clause License\t1",
	"3D-Slicer-1.0\t3D Slicer License v1.0\t0",
	"AAL\tAttribution Assurance License\t1",
	"ADSL\tAmazon Digital Services License\t0",
	"AFL-1.1\tAcademic Free License v1.1\t3",
	"AFL-1.2\tAcademic Free License v1.2\t3",
	"AFL-2.0\tAcademic Free License v2.0\t3",
	"AFL-2.1\tAcademic Free License v2.1\t3",
	"AFL-3.0\tAcademic Free License v3.0\t3",
	"AGPL-1.0\tAffero General Public License v1.0\t2",
	"AGPL-1.0-only\tAffero General Public License v1.0 only\t0",
	"AGPL-1.0-or-later\tAffero General Public License v1.0 or later\t0",
	"AGPL-3.0\tGNU Affero General Public License v3.0\t3",
	"AGPL-3.0-only\tGNU Affero General Public License v3.0 only\t3",
	"AGPL-3.0-or-later\tGNU Affero General Public License v3.0 or later\t3",
	"ALGLIB-Documentation\tALGLIB Documentation License\t1",
	"AMD-newlib\tAMD newlib License\t0",
	"AMDPLPA\tAMD's plpa_map.c License\t0",
	"AML\tApple MIT License\t0",
	"AML-glslang\tAML glslang variant License\t0",
	"AMPAS\tAcademy of Motion Picture Arts and Sciences BSD\t0",
	"ANTLR-PD\tANTLR Software Rights Notice\t0",
	"ANTLR-PD-fallback\tANTLR Software Rights Notice with license fallback\t0",
	"APAFML\tAdobe Postscript AFM License\t0",
	"APL-1.0\tAdaptive Public License 1.0\t1",
	"APSL-1.0\tApple Public Source License 1.0\t1",
	"APSL-1.1\tApple Public Source License 1.1\t1",
	"APSL-1.2\tApple Public Source License 1.2\t1",
	"APSL-2.0\tApple Public Source License 2.0\t3",
	"ASWF-Digital-Assets-1.0\tASWF Digital Assets License version 1.0\t0",
	"ASWF-Digital-Assets-1.1\tASWF Digital Assets License 1.1\t0",
	"Abstyles\tAbstyles License\t0",
	"AdaCore-doc\tAdaCore Doc License\t0",
	"Adobe-2006\tAdobe Systems Incorporated Source Code License Agreement\t0",
	"Adobe-Display-PostScript\tAdobe Display PostScript License\t0",
	"Adobe-Glyph\tAdobe Glyph List License\t0",
	"Adobe-Utopia\tAdobe Utopia Font License\t0",
	"Advanced-Cryptics-Dictionary\tAdvanced Cryptics Dictionary License\t0",
	"Afmparse\tAfmparse License\t0",
	"Aladdin\tAladdin Free Public License\t0",
	"Apache-1.0\tApache License 1.0\t2",
	"Apache-1.1\tApache License 1.1\t3",
	"Apache-2.0\tApache License 2.0\t3",
	"App-s2p\tApp::s2p License\t0",
	"Arphic-1999\tArphic Public License\t0",
	"Artistic-1.0\tArtistic License 1.0\t1",
	"Artistic-1.0-Perl\tArtistic License 1.0 (Perl)\t1",
	"Artistic-1.0-cl8\tArtistic License 1.0 w/clause 8\t1",
	"Artistic-2.0\tArtistic License 2.0\t3",
	"Artistic-dist\tArtistic License 1.0 (dist)\t0",
	"Aspell-RU\tAspell Russian License\t0",
	"BOLA-1.1\tBuena Onda License Agreement v1.1\t0",
	"BSD-1-Clause\tBSD 1-Clause License\t1",
	'BSD-2-Clause\tBSD 2-Clause "Simplified" License\t3',
	"BSD-2-Clause-Darwin\tBSD 2-Clause - Ian Darwin variant\t0",
	"BSD-2-Clause-FreeBSD\tBSD 2-Clause FreeBSD License\t2",
	"BSD-2-Clause-NetBSD\tBSD 2-Clause NetBSD License\t2",
	"BSD-2-Clause-Patent\tBSD-2-Clause Plus Patent License\t1",
	"BSD-2-Clause-Views\tBSD 2-Clause with views sentence\t0",
	"BSD-2-Clause-first-lines\tBSD 2-Clause - first lines requirement\t0",
	"BSD-2-Clause-pkgconf-disclaimer\tBSD 2-Clause pkgconf disclaimer variant\t0",
	'BSD-3-Clause\tBSD 3-Clause "New" or "Revised" License\t3',
	"BSD-3-Clause-Attribution\tBSD with attribution\t0",
	"BSD-3-Clause-Clear\tBSD 3-Clause Clear License\t2",
	"BSD-3-Clause-HP\tHewlett-Packard BSD variant license\t0",
	"BSD-3-Clause-LBNL\tLawrence Berkeley National Labs BSD variant license\t1",
	"BSD-3-Clause-Modification\tBSD 3-Clause Modification\t0",
	"BSD-3-Clause-No-Military-License\tBSD 3-Clause No Military License\t0",
	"BSD-3-Clause-No-Nuclear-License\tBSD 3-Clause No Nuclear License\t0",
	"BSD-3-Clause-No-Nuclear-License-2014\tBSD 3-Clause No Nuclear License 2014\t0",
	"BSD-3-Clause-No-Nuclear-Warranty\tBSD 3-Clause No Nuclear Warranty\t0",
	"BSD-3-Clause-Open-MPI\tBSD 3-Clause Open MPI variant\t1",
	"BSD-3-Clause-Sun\tBSD 3-Clause Sun Microsystems\t0",
	"BSD-3-Clause-Tso\tBSD 3-Clause Tso variant\t0",
	"BSD-3-Clause-acpica\tBSD 3-Clause acpica variant\t0",
	"BSD-3-Clause-flex\tBSD 3-Clause Flex variant\t0",
	'BSD-4-Clause\tBSD 4-Clause "Original" or "Old" License\t2',
	"BSD-4-Clause-Shortened\tBSD 4 Clause Shortened\t0",
	"BSD-4-Clause-UC\tBSD-4-Clause (University of California-Specific)\t0",
	"BSD-4.3RENO\tBSD 4.3 RENO License\t0",
	"BSD-4.3TAHOE\tBSD 4.3 TAHOE License\t0",
	"BSD-Advertising-Acknowledgement\tBSD Advertising Acknowledgement License\t0",
	"BSD-Attribution-HPND-disclaimer\tBSD with Attribution and HPND disclaimer\t0",
	"BSD-Inferno-Nettverk\tBSD-Inferno-Nettverk\t0",
	"BSD-Mark-Modifications\tBSD Mark Modifications License\t0",
	"BSD-Protection\tBSD Protection License\t0",
	"BSD-Source-Code\tBSD Source Code Attribution\t0",
	"BSD-Source-beginning-file\tBSD Source Code Attribution - beginning of file variant\t0",
	"BSD-Systemics\tSystemics BSD variant license\t0",
	"BSD-Systemics-W3Works\tSystemics W3Works BSD variant license\t0",
	"BSL-1.0\tBoost Software License 1.0\t3",
	"BUSL-1.1\tBusiness Source License 1.1\t0",
	"Baekmuk\tBaekmuk License\t0",
	"Bahyph\tBahyph License\t0",
	"Barr\tBarr License\t0",
	"Beerware\tBeerware License\t0",
	"BitTorrent-1.0\tBitTorrent Open Source License v1.0\t0",
	"BitTorrent-1.1\tBitTorrent Open Source License v1.1\t2",
	"Bitstream-Charter\tBitstream Charter Font License\t0",
	"Bitstream-Vera\tBitstream Vera Font License\t0",
	"BlueOak-1.0.0\tBlue Oak Model License 1.0.0\t1",
	"Boehm-GC\tBoehm-Demers-Weiser GC License\t0",
	"Boehm-GC-without-fee\tBoehm-Demers-Weiser GC License (without fee)\t0",
	"Borceux\tBorceux license\t0",
	"Brian-Gladman-2-Clause\tBrian Gladman 2-Clause License\t0",
	"Brian-Gladman-3-Clause\tBrian Gladman 3-Clause License\t0",
	"Buddy\tBuddy License\t0",
	"C-UDA-1.0\tComputational Use of Data Agreement v1.0\t0",
	"CAL-1.0\tCryptographic Autonomy License 1.0\t1",
	"CAL-1.0-Combined-Work-Exception\tCryptographic Autonomy License 1.0 (Combined Work Exception)\t1",
	"CAPEC-tou\tCommon Attack    Pattern Enumeration and Classification License\t0",
	"CATOSL-1.1\tComputer Associates Trusted Open Source License 1.1\t1",
	"CC-BY-1.0\tCreative Commons Attribution 1.0 Generic\t0",
	"CC-BY-2.0\tCreative Commons Attribution 2.0 Generic\t0",
	"CC-BY-2.5\tCreative Commons Attribution 2.5 Generic\t0",
	"CC-BY-2.5-AU\tCreative Commons Attribution 2.5 Australia\t0",
	"CC-BY-3.0\tCreative Commons Attribution 3.0 Unported\t0",
	"CC-BY-3.0-AT\tCreative Commons Attribution 3.0 Austria\t0",
	"CC-BY-3.0-AU\tCreative Commons Attribution 3.0 Australia\t0",
	"CC-BY-3.0-DE\tCreative Commons Attribution 3.0 Germany\t0",
	"CC-BY-3.0-IGO\tCreative Commons Attribution 3.0 IGO\t0",
	"CC-BY-3.0-NL\tCreative Commons Attribution 3.0 Netherlands\t0",
	"CC-BY-3.0-US\tCreative Commons Attribution 3.0 United States\t0",
	"CC-BY-4.0\tCreative Commons Attribution 4.0 International\t2",
	"CC-BY-NC-1.0\tCreative Commons Attribution Non Commercial 1.0 Generic\t0",
	"CC-BY-NC-2.0\tCreative Commons Attribution Non Commercial 2.0 Generic\t0",
	"CC-BY-NC-2.5\tCreative Commons Attribution Non Commercial 2.5 Generic\t0",
	"CC-BY-NC-3.0\tCreative Commons Attribution Non Commercial 3.0 Unported\t0",
	"CC-BY-NC-3.0-DE\tCreative Commons Attribution Non Commercial 3.0 Germany\t0",
	"CC-BY-NC-4.0\tCreative Commons Attribution Non Commercial 4.0 International\t0",
	"CC-BY-NC-ND-1.0\tCreative Commons Attribution Non Commercial No Derivatives 1.0 Generic\t0",
	"CC-BY-NC-ND-2.0\tCreative Commons Attribution Non Commercial No Derivatives 2.0 Generic\t0",
	"CC-BY-NC-ND-2.5\tCreative Commons Attribution Non Commercial No Derivatives 2.5 Generic\t0",
	"CC-BY-NC-ND-3.0\tCreative Commons Attribution Non Commercial No Derivatives 3.0 Unported\t0",
	"CC-BY-NC-ND-3.0-DE\tCreative Commons Attribution Non Commercial No Derivatives 3.0 Germany\t0",
	"CC-BY-NC-ND-3.0-IGO\tCreative Commons Attribution Non Commercial No Derivatives 3.0 IGO\t0",
	"CC-BY-NC-ND-4.0\tCreative Commons Attribution Non Commercial No Derivatives 4.0 International\t0",
	"CC-BY-NC-SA-1.0\tCreative Commons Attribution Non Commercial Share Alike 1.0 Generic\t0",
	"CC-BY-NC-SA-2.0\tCreative Commons Attribution Non Commercial Share Alike 2.0 Generic\t0",
	"CC-BY-NC-SA-2.0-DE\tCreative Commons Attribution Non Commercial Share Alike 2.0 Germany\t0",
	"CC-BY-NC-SA-2.0-FR\tCreative Commons Attribution-NonCommercial-ShareAlike 2.0 France\t0",
	"CC-BY-NC-SA-2.0-UK\tCreative Commons Attribution Non Commercial Share Alike 2.0 England and Wales\t0",
	"CC-BY-NC-SA-2.5\tCreative Commons Attribution Non Commercial Share Alike 2.5 Generic\t0",
	"CC-BY-NC-SA-3.0\tCreative Commons Attribution Non Commercial Share Alike 3.0 Unported\t0",
	"CC-BY-NC-SA-3.0-DE\tCreative Commons Attribution Non Commercial Share Alike 3.0 Germany\t0",
	"CC-BY-NC-SA-3.0-IGO\tCreative Commons Attribution Non Commercial Share Alike 3.0 IGO\t0",
	"CC-BY-NC-SA-4.0\tCreative Commons Attribution Non Commercial Share Alike 4.0 International\t0",
	"CC-BY-ND-1.0\tCreative Commons Attribution No Derivatives 1.0 Generic\t0",
	"CC-BY-ND-2.0\tCreative Commons Attribution No Derivatives 2.0 Generic\t0",
	"CC-BY-ND-2.5\tCreative Commons Attribution No Derivatives 2.5 Generic\t0",
	"CC-BY-ND-3.0\tCreative Commons Attribution No Derivatives 3.0 Unported\t0",
	"CC-BY-ND-3.0-DE\tCreative Commons Attribution No Derivatives 3.0 Germany\t0",
	"CC-BY-ND-4.0\tCreative Commons Attribution No Derivatives 4.0 International\t0",
	"CC-BY-SA-1.0\tCreative Commons Attribution Share Alike 1.0 Generic\t0",
	"CC-BY-SA-2.0\tCreative Commons Attribution Share Alike 2.0 Generic\t0",
	"CC-BY-SA-2.0-UK\tCreative Commons Attribution Share Alike 2.0 England and Wales\t0",
	"CC-BY-SA-2.1-JP\tCreative Commons Attribution Share Alike 2.1 Japan\t0",
	"CC-BY-SA-2.5\tCreative Commons Attribution Share Alike 2.5 Generic\t0",
	"CC-BY-SA-3.0\tCreative Commons Attribution Share Alike 3.0 Unported\t0",
	"CC-BY-SA-3.0-AT\tCreative Commons Attribution Share Alike 3.0 Austria\t0",
	"CC-BY-SA-3.0-DE\tCreative Commons Attribution Share Alike 3.0 Germany\t0",
	"CC-BY-SA-3.0-IGO\tCreative Commons Attribution-ShareAlike 3.0 IGO\t0",
	"CC-BY-SA-4.0\tCreative Commons Attribution Share Alike 4.0 International\t2",
	"CC-PDDC\tCreative Commons Public Domain Dedication and Certification\t0",
	"CC-PDM-1.0\tCreative    Commons Public Domain Mark 1.0 Universal\t0",
	"CC-SA-1.0\tCreative Commons Share Alike 1.0 Generic\t0",
	"CC0-1.0\tCreative Commons Zero v1.0 Universal\t2",
	"CDDL-1.0\tCommon Development and Distribution License 1.0\t3",
	"CDDL-1.1\tCommon Development and Distribution License 1.1\t0",
	"CDL-1.0\tCommon Documentation License 1.0\t0",
	"CDLA-Permissive-1.0\tCommunity Data License Agreement Permissive 1.0\t0",
	"CDLA-Permissive-2.0\tCommunity Data License Agreement Permissive 2.0\t0",
	"CDLA-Sharing-1.0\tCommunity Data License Agreement Sharing 1.0\t0",
	"CECILL-1.0\tCeCILL Free Software License Agreement v1.0\t0",
	"CECILL-1.1\tCeCILL Free Software License Agreement v1.1\t0",
	"CECILL-2.0\tCeCILL Free Software License Agreement v2.0\t2",
	"CECILL-2.1\tCeCILL Free Software License Agreement v2.1\t1",
	"CECILL-B\tCeCILL-B Free Software License Agreement\t2",
	"CECILL-C\tCeCILL-C Free Software License Agreement\t2",
	"CERN-OHL-1.1\tCERN Open Hardware Licence v1.1\t0",
	"CERN-OHL-1.2\tCERN Open Hardware Licence v1.2\t0",
	"CERN-OHL-P-2.0\tCERN Open Hardware Licence Version 2 - Permissive\t1",
	"CERN-OHL-S-2.0\tCERN Open Hardware Licence Version 2 - Strongly Reciprocal\t1",
	"CERN-OHL-W-2.0\tCERN Open Hardware Licence Version 2 - Weakly Reciprocal\t1",
	"CFITSIO\tCFITSIO License\t0",
	"CMU-Mach\tCMU Mach License\t0",
	"CMU-Mach-nodoc\tCMU    Mach - no notices-in-documentation variant\t0",
	"CNRI-Jython\tCNRI Jython License\t0",
	"CNRI-Python\tCNRI Python License\t1",
	"CNRI-Python-GPL-Compatible\tCNRI Python Open Source GPL Compatible License Agreement\t0",
	"COIL-1.0\tCopyfree Open Innovation License\t0",
	"CPAL-1.0\tCommon Public Attribution License 1.0\t3",
	"CPL-1.0\tCommon Public License 1.0\t3",
	"CPOL-1.02\tCode Project Open License 1.02\t0",
	"CUA-OPL-1.0\tCUA Office Public License v1.0\t1",
	"Caldera\tCaldera License\t0",
	"Caldera-no-preamble\tCaldera License (without preamble)\t0",
	"Catharon\tCatharon License\t0",
	"ClArtistic\tClarified Artistic License\t2",
	"Clips\tClips License\t0",
	"Community-Spec-1.0\tCommunity Specification License 1.0\t0",
	"Condor-1.1\tCondor Public License v1.1\t2",
	"Cornell-Lossless-JPEG\tCornell Lossless JPEG License\t0",
	"Cronyx\tCronyx License\t0",
	"Crossword\tCrossword License\t0",
	"CryptoSwift\tCryptoSwift License\t0",
	"CrystalStacker\tCrystalStacker License\t0",
	"Cube\tCube License\t0",
	"D-FSL-1.0\tDeutsche Freie Software Lizenz\t0",
	"DEC-3-Clause\tDEC 3-Clause License\t0",
	"DL-DE-BY-2.0\tData licence Germany – attribution – version 2.0\t0",
	"DL-DE-ZERO-2.0\tData licence Germany – zero – version 2.0\t0",
	"DOC\tDOC License\t0",
	"DRL-1.0\tDetection Rule License 1.0\t0",
	"DRL-1.1\tDetection Rule License 1.1\t0",
	"DSDP\tDSDP License\t0",
	"DocBook-DTD\tDocBook DTD License\t0",
	"DocBook-Schema\tDocBook Schema License\t0",
	"DocBook-Stylesheet\tDocBook Stylesheet License\t0",
	"DocBook-XML\tDocBook XML License\t0",
	"Dotseqn\tDotseqn License\t0",
	"ECL-1.0\tEducational Community License v1.0\t1",
	"ECL-2.0\tEducational Community License v2.0\t3",
	"EFL-1.0\tEiffel Forum License v1.0\t1",
	"EFL-2.0\tEiffel Forum License v2.0\t3",
	"EPICS\tEPICS Open License\t0",
	"EPL-1.0\tEclipse Public License 1.0\t3",
	"EPL-2.0\tEclipse Public License 2.0\t3",
	"ESA-PL-permissive-2.4\tEuropean Space Agency Public License – v2.4 – Permissive (Type 3)\t0",
	"ESA-PL-strong-copyleft-2.4\tEuropean Space Agency Public License (ESA-PL) - V2.4 - Strong Copyleft (Type 1)\t0",
	"ESA-PL-weak-copyleft-2.4\tEuropean Space Agency Public License – v2.4 – Weak Copyleft (Type 2)\t0",
	"EUDatagrid\tEU DataGrid Software License\t3",
	"EUPL-1.0\tEuropean Union Public License 1.0\t0",
	"EUPL-1.1\tEuropean Union Public License 1.1\t3",
	"EUPL-1.2\tEuropean Union Public License 1.2\t3",
	"Elastic-2.0\tElastic License 2.0\t0",
	"Entessa\tEntessa Public License v1.0\t1",
	"ErlPL-1.1\tErlang Public License v1.1\t0",
	"Eurosym\tEurosym License\t0",
	"FBM\tFuzzy Bitmap License\t0",
	"FDK-AAC\tFraunhofer FDK AAC Codec Library\t0",
	"FSFAP\tFSF All Permissive License\t2",
	"FSFAP-no-warranty-disclaimer\tFSF All Permissive License (without Warranty)\t0",
	"FSFUL\tFSF Unlimited License\t0",
	"FSFULLR\tFSF Unlimited License (with License Retention)\t0",
	"FSFULLRSD\tFSF Unlimited License (with License Retention and Short Disclaimer)\t0",
	"FSFULLRWD\tFSF Unlimited License (With License Retention and Warranty Disclaimer)\t0",
	"FSL-1.1-ALv2\tFunctional Source License, Version 1.1, ALv2 Future License\t0",
	"FSL-1.1-MIT\tFunctional Source License, Version 1.1, MIT Future License\t0",
	"FTL\tFreetype Project License\t2",
	"Fair\tFair License\t1",
	"Ferguson-Twofish\tFerguson Twofish License\t0",
	"Frameworx-1.0\tFrameworx Open License 1.0\t1",
	"FreeBSD-DOC\tFreeBSD Documentation License\t0",
	"FreeImage\tFreeImage Public License v1.0\t0",
	"Furuseth\tFuruseth License\t0",
	"GCR-docs\tGnome GCR Documentation License\t0",
	"GD\tGD License\t0",
	"GFDL-1.1\tGNU Free Documentation License v1.1\t2",
	"GFDL-1.1-invariants-only\tGNU Free Documentation License v1.1 only - invariants\t0",
	"GFDL-1.1-invariants-or-later\tGNU Free Documentation License v1.1 or later - invariants\t0",
	"GFDL-1.1-no-invariants-only\tGNU Free Documentation License v1.1 only - no invariants\t0",
	"GFDL-1.1-no-invariants-or-later\tGNU Free Documentation License v1.1 or later - no invariants\t0",
	"GFDL-1.1-only\tGNU Free Documentation License v1.1 only\t2",
	"GFDL-1.1-or-later\tGNU Free Documentation License v1.1 or later\t2",
	"GFDL-1.2\tGNU Free Documentation License v1.2\t2",
	"GFDL-1.2-invariants-only\tGNU Free Documentation License v1.2 only - invariants\t0",
	"GFDL-1.2-invariants-or-later\tGNU Free Documentation License v1.2 or later - invariants\t0",
	"GFDL-1.2-no-invariants-only\tGNU Free Documentation License v1.2 only - no invariants\t0",
	"GFDL-1.2-no-invariants-or-later\tGNU Free Documentation License v1.2 or later - no invariants\t0",
	"GFDL-1.2-only\tGNU Free Documentation License v1.2 only\t2",
	"GFDL-1.2-or-later\tGNU Free Documentation License v1.2 or later\t2",
	"GFDL-1.3\tGNU Free Documentation License v1.3\t2",
	"GFDL-1.3-invariants-only\tGNU Free Documentation License v1.3 only - invariants\t0",
	"GFDL-1.3-invariants-or-later\tGNU Free Documentation License v1.3 or later - invariants\t0",
	"GFDL-1.3-no-invariants-only\tGNU Free Documentation License v1.3 only - no invariants\t0",
	"GFDL-1.3-no-invariants-or-later\tGNU Free Documentation License v1.3 or later - no invariants\t0",
	"GFDL-1.3-only\tGNU Free Documentation License v1.3 only\t2",
	"GFDL-1.3-or-later\tGNU Free Documentation License v1.3 or later\t2",
	"GL2PS\tGL2PS License\t0",
	"GLWTPL\tGood Luck With That Public License\t0",
	"GPL-1.0\tGNU General Public License v1.0 only\t0",
	"GPL-1.0-only\tGNU General Public License v1.0 only\t0",
	"GPL-1.0-or-later\tGNU General Public License v1.0 or later\t0",
	"GPL-2.0\tGNU General Public License v2.0 only\t3",
	"GPL-2.0-only\tGNU General Public License v2.0 only\t3",
	"GPL-2.0-or-later\tGNU General Public License v2.0 or later\t3",
	"GPL-2.0-with-GCC-exception\tGNU General Public License v2.0 w/GCC Runtime Library exception\t0",
	"GPL-2.0-with-autoconf-exception\tGNU General Public License v2.0 w/Autoconf exception\t0",
	"GPL-2.0-with-bison-exception\tGNU General Public License v2.0 w/Bison exception\t0",
	"GPL-2.0-with-classpath-exception\tGNU General Public License v2.0 w/Classpath exception\t0",
	"GPL-2.0-with-font-exception\tGNU General Public License v2.0 w/Font exception\t0",
	"GPL-3.0\tGNU General Public License v3.0 only\t3",
	"GPL-3.0-only\tGNU General Public License v3.0 only\t3",
	"GPL-3.0-or-later\tGNU General Public License v3.0 or later\t3",
	"GPL-3.0-with-GCC-exception\tGNU General Public License v3.0 w/GCC Runtime Library exception\t1",
	"GPL-3.0-with-autoconf-exception\tGNU General Public License v3.0 w/Autoconf exception\t0",
	"Game-Programming-Gems\tGame Programming Gems License\t0",
	"Giftware\tGiftware License\t0",
	"Glide\t3dfx Glide License\t0",
	"Glulxe\tGlulxe License\t0",
	"Graphics-Gems\tGraphics Gems License\t0",
	"Gutmann\tGutmann License\t0",
	"HDF5\tHDF5 License\t0",
	"HIDAPI\tHIDAPI License\t0",
	"HP-1986\tHewlett-Packard 1986 License\t0",
	"HP-1989\tHewlett-Packard 1989 License\t0",
	"HPND\tHistorical Permission Notice and Disclaimer\t3",
	"HPND-DEC\tHistorical Permission Notice and Disclaimer - DEC variant\t0",
	"HPND-Fenneberg-Livingston\tHistorical Permission Notice and Disclaimer - Fenneberg-Livingston variant\t0",
	"HPND-INRIA-IMAG\tHistorical Permission Notice and Disclaimer    - INRIA-IMAG variant\t0",
	"HPND-Intel\tHistorical Permission Notice and Disclaimer - Intel variant\t0",
	"HPND-Kevlin-Henney\tHistorical Permission Notice and Disclaimer - Kevlin Henney variant\t0",
	"HPND-MIT-disclaimer\tHistorical Permission Notice and Disclaimer with MIT disclaimer\t0",
	"HPND-Markus-Kuhn\tHistorical Permission Notice and Disclaimer - Markus Kuhn variant\t0",
	"HPND-Netrek\tHistorical Permission Notice and Disclaimer - Netrek variant\t0",
	"HPND-Pbmplus\tHistorical Permission Notice and Disclaimer - Pbmplus variant\t0",
	"HPND-SMC\tHistorical Permission Notice and Disclaimer - SMC variant\t0",
	"HPND-UC\tHistorical Permission Notice and Disclaimer - University of California variant\t0",
	"HPND-UC-export-US\tHistorical Permission Notice and Disclaimer - University of California, US export warning\t0",
	"HPND-doc\tHistorical Permission Notice and Disclaimer - documentation variant\t0",
	"HPND-doc-sell\tHistorical Permission Notice and Disclaimer - documentation sell variant\t0",
	"HPND-export-US\tHPND with US Government export control warning\t0",
	"HPND-export-US-acknowledgement\tHPND with US Government export control warning and acknowledgment\t0",
	"HPND-export-US-modify\tHPND with US Government export control warning and modification rqmt\t0",
	"HPND-export2-US\tHPND with US Government export control and 2 disclaimers\t0",
	"HPND-merchantability-variant\tHistorical Permission Notice and Disclaimer - merchantability variant\t0",
	"HPND-sell-MIT-disclaimer-xserver\tHistorical Permission Notice and Disclaimer - sell xserver variant with MIT disclaimer\t0",
	"HPND-sell-regexpr\tHistorical Permission Notice and Disclaimer - sell regexpr variant\t0",
	"HPND-sell-variant\tHistorical Permission Notice and Disclaimer - sell variant\t0",
	"HPND-sell-variant-MIT-disclaimer\tHPND sell variant with MIT disclaimer\t0",
	"HPND-sell-variant-MIT-disclaimer-rev\tHPND sell variant with MIT disclaimer - reverse\t0",
	"HPND-sell-variant-critical-systems\tHPND - sell variant with safety critical systems clause\t0",
	"HTMLTIDY\tHTML Tidy License\t0",
	"HaskellReport\tHaskell Language Report License\t0",
	"Hippocratic-2.1\tHippocratic License 2.1\t0",
	"IBM-pibs\tIBM PowerPC Initialization and Boot Software\t0",
	"ICU\tICU License\t1",
	"IEC-Code-Components-EULA\tIEC    Code Components End-user licence agreement\t0",
	"IJG\tIndependent JPEG Group License\t2",
	"IJG-short\tIndependent JPEG Group License - short\t0",
	"IPA\tIPA Font License\t3",
	"IPL-1.0\tIBM Public License v1.0\t3",
	"ISC\tISC License\t3",
	"ISC-Veillard\tISC Veillard variant\t0",
	"ISO-permission\tISO permission notice\t0",
	"ImageMagick\tImageMagick License\t0",
	"Imlib2\tImlib2 License\t2",
	"Info-ZIP\tInfo-ZIP License\t0",
	"Inner-Net-2.0\tInner Net License v2.0\t0",
	"InnoSetup\tInno Setup License\t0",
	"Intel\tIntel Open Source License\t3",
	"Intel-ACPI\tIntel ACPI Software License Agreement\t0",
	"Interbase-1.0\tInterbase Public License v1.0\t0",
	"JPL-image\tJPL Image Use Policy\t0",
	"JPNIC\tJapan Network Information Center License\t0",
	"JSON\tJSON License\t0",
	"Jam\tJam License\t1",
	"JasPer-2.0\tJasPer License\t0",
	"Kastrup\tKastrup License\t0",
	"Kazlib\tKazlib License\t0",
	"Knuth-CTAN\tKnuth CTAN License\t0",
	"LAL-1.2\tLicence Art Libre 1.2\t0",
	"LAL-1.3\tLicence Art Libre 1.3\t0",
	"LGPL-2.0\tGNU Library General Public License v2 only\t1",
	"LGPL-2.0-only\tGNU Library General Public License v2 only\t1",
	"LGPL-2.0-or-later\tGNU Library General Public License v2 or later\t1",
	"LGPL-2.1\tGNU Lesser General Public License v2.1 only\t3",
	"LGPL-2.1-only\tGNU Lesser General Public License v2.1 only\t3",
	"LGPL-2.1-or-later\tGNU Lesser General Public License v2.1 or later\t3",
	"LGPL-3.0\tGNU Lesser General Public License v3.0 only\t3",
	"LGPL-3.0-only\tGNU Lesser General Public License v3.0 only\t3",
	"LGPL-3.0-or-later\tGNU Lesser General Public License v3.0 or later\t3",
	"LGPLLR\tLesser General Public License For Linguistic Resources\t0",
	"LOOP\tCommon Lisp LOOP License\t0",
	"LPD-document\tLPD Documentation License\t0",
	"LPL-1.0\tLucent Public License Version 1.0\t1",
	"LPL-1.02\tLucent Public License v1.02\t3",
	"LPPL-1.0\tLaTeX Project Public License v1.0\t0",
	"LPPL-1.1\tLaTeX Project Public License v1.1\t0",
	"LPPL-1.2\tLaTeX Project Public License v1.2\t2",
	"LPPL-1.3a\tLaTeX Project Public License v1.3a\t2",
	"LPPL-1.3c\tLaTeX Project Public License v1.3c\t1",
	"LZMA-SDK-9.11-to-9.20\tLZMA SDK License (versions 9.11 to 9.20)\t0",
	"LZMA-SDK-9.22\tLZMA SDK License (versions 9.22 and beyond)\t0",
	"Latex2e\tLatex2e License\t0",
	"Latex2e-translated-notice\tLatex2e with translated notice permission\t0",
	"Leptonica\tLeptonica License\t0",
	"LiLiQ-P-1.1\tLicence Libre du Québec – Permissive version 1.1\t1",
	"LiLiQ-R-1.1\tLicence Libre du Québec – Réciprocité version 1.1\t1",
	"LiLiQ-Rplus-1.1\tLicence Libre du Québec – Réciprocité forte version 1.1\t1",
	"Libpng\tlibpng License\t0",
	"Linux-OpenIB\tLinux Kernel Variant of OpenIB.org license\t0",
	"Linux-man-pages-1-para\tLinux man-pages - 1 paragraph\t0",
	"Linux-man-pages-copyleft\tLinux man-pages Copyleft\t0",
	"Linux-man-pages-copyleft-2-para\tLinux man-pages Copyleft - 2 paragraphs\t0",
	"Linux-man-pages-copyleft-var\tLinux man-pages Copyleft Variant\t0",
	"Lucida-Bitmap-Fonts\tLucida Bitmap Fonts License\t0",
	"MIPS\tMIPS License\t0",
	"MIT\tMIT License\t3",
	"MIT-0\tMIT No Attribution\t1",
	"MIT-CMU\tCMU License\t0",
	"MIT-Click\tMIT Click License\t0",
	"MIT-Festival\tMIT Festival Variant\t0",
	"MIT-Khronos-old\tMIT Khronos - old variant\t0",
	"MIT-Modern-Variant\tMIT License Modern Variant\t1",
	"MIT-STK\tMIT-STK License\t0",
	"MIT-Wu\tMIT Tom Wu Variant\t0",
	"MIT-advertising\tEnlightenment License (e16)\t0",
	"MIT-enna\tenna License\t0",
	"MIT-feh\tfeh License\t0",
	"MIT-open-group\tMIT Open Group variant\t0",
	"MIT-testregex\tMIT testregex Variant\t0",
	"MITNFA\tMIT +no-false-attribs license\t0",
	"MMIXware\tMMIXware License\t0",
	"MMPL-1.0.1\tMinecraft Mod Public License v1.0.1\t0",
	"MPEG-SSG\tMPEG Software Simulation\t0",
	"MPL-1.0\tMozilla Public License 1.0\t1",
	"MPL-1.1\tMozilla Public License 1.1\t3",
	"MPL-2.0\tMozilla Public License 2.0\t3",
	"MPL-2.0-no-copyleft-exception\tMozilla Public License 2.0 (no copyleft exception)\t1",
	"MS-LPL\tMicrosoft Limited Public License\t0",
	"MS-PL\tMicrosoft Public License\t3",
	"MS-RL\tMicrosoft Reciprocal License\t3",
	"MTLL\tMatrix Template Library License\t0",
	"Mackerras-3-Clause\tMackerras 3-Clause License\t0",
	"Mackerras-3-Clause-acknowledgment\tMackerras 3-Clause - acknowledgment variant\t0",
	"MakeIndex\tMakeIndex License\t0",
	"Martin-Birgmeier\tMartin Birgmeier License\t0",
	"McPhee-slideshow\tMcPhee Slideshow License\t0",
	"Minpack\tMinpack License\t0",
	"MirOS\tThe MirOS Licence\t1",
	"Motosoto\tMotosoto License\t1",
	"MulanPSL-1.0\tMulan Permissive Software License, Version 1\t0",
	"MulanPSL-2.0\tMulan Permissive Software License, Version 2\t1",
	"Multics\tMultics License\t1",
	"Mup\tMup License\t0",
	"NAIST-2003\tNara Institute of Science and Technology License (2003)\t0",
	"NASA-1.3\tNASA Open Source Agreement 1.3\t1",
	"NBPL-1.0\tNet Boolean Public License v1\t0",
	"NCBI-PD\tNCBI Public Domain Notice\t0",
	"NCGL-UK-2.0\tNon-Commercial Government Licence\t0",
	"NCL\tNCL Source Code License\t0",
	"NCSA\tUniversity of Illinois/NCSA Open Source License\t3",
	"NGPL\tNethack General Public License\t1",
	"NICTA-1.0\tNICTA Public Software License, Version 1.0\t0",
	"NIST-PD\tNIST Public Domain Notice\t0",
	"NIST-PD-TNT\tNIST    Public Domain Notice TNT variant\t0",
	"NIST-PD-fallback\tNIST Public Domain Notice with license fallback\t0",
	"NIST-Software\tNIST Software License\t0",
	"NLOD-1.0\tNorwegian Licence for Open Government Data (NLOD) 1.0\t0",
	"NLOD-2.0\tNorwegian Licence for Open Government Data (NLOD) 2.0\t0",
	"NLPL\tNo Limit Public License\t0",
	"NOSL\tNetizen Open Source License\t2",
	"NPL-1.0\tNetscape Public License v1.0\t2",
	"NPL-1.1\tNetscape Public License v1.1\t2",
	"NPOSL-3.0\tNon-Profit Open Software License 3.0\t1",
	"NRL\tNRL License\t0",
	"NTIA-PD\tNTIA Public Domain Notice\t0",
	"NTP\tNTP License\t1",
	"NTP-0\tNTP No Attribution\t0",
	"Naumen\tNaumen Public License\t1",
	"Net-SNMP\tNet-SNMP License\t0",
	"NetCDF\tNetCDF license\t0",
	"Newsletr\tNewsletr License\t0",
	"Nokia\tNokia Open Source License\t3",
	"Noweb\tNoweb License\t0",
	"Nunit\tNunit License\t2",
	"O-UDA-1.0\tOpen Use of Data Agreement v1.0\t0",
	"OAR\tOAR License\t0",
	"OCCT-PL\tOpen CASCADE Technology Public License\t0",
	"OCLC-2.0\tOCLC Research Public License 2.0\t1",
	"ODC-By-1.0\tOpen Data Commons Attribution License v1.0\t0",
	"ODbL-1.0\tOpen Data Commons Open Database License v1.0\t2",
	"OFFIS\tOFFIS License\t0",
	"OFL-1.0\tSIL Open Font License 1.0\t2",
	"OFL-1.0-RFN\tSIL Open Font License 1.0 with Reserved Font Name\t0",
	"OFL-1.0-no-RFN\tSIL Open Font License 1.0 with no Reserved Font Name\t0",
	"OFL-1.1\tSIL Open Font License 1.1\t3",
	"OFL-1.1-RFN\tSIL Open Font License 1.1 with Reserved Font Name\t1",
	"OFL-1.1-no-RFN\tSIL Open Font License 1.1 with no Reserved Font Name\t1",
	"OGC-1.0\tOGC Software License, Version 1.0\t0",
	"OGDL-Taiwan-1.0\tTaiwan Open Government Data License, version 1.0\t0",
	"OGL-Canada-2.0\tOpen Government Licence - Canada\t0",
	"OGL-UK-1.0\tOpen Government Licence v1.0\t0",
	"OGL-UK-2.0\tOpen Government Licence v2.0\t0",
	"OGL-UK-3.0\tOpen Government Licence v3.0\t0",
	"OGTSL\tOpen Group Test Suite License\t1",
	"OLDAP-1.1\tOpen LDAP Public License v1.1\t0",
	"OLDAP-1.2\tOpen LDAP Public License v1.2\t0",
	"OLDAP-1.3\tOpen LDAP Public License v1.3\t0",
	"OLDAP-1.4\tOpen LDAP Public License v1.4\t0",
	"OLDAP-2.0\tOpen LDAP Public License v2.0 (or possibly 2.0A and 2.0B)\t0",
	"OLDAP-2.0.1\tOpen LDAP Public License v2.0.1\t0",
	"OLDAP-2.1\tOpen LDAP Public License v2.1\t0",
	"OLDAP-2.2\tOpen LDAP Public License v2.2\t0",
	"OLDAP-2.2.1\tOpen LDAP Public License v2.2.1\t0",
	"OLDAP-2.2.2\tOpen LDAP Public License 2.2.2\t0",
	"OLDAP-2.3\tOpen LDAP Public License v2.3\t2",
	"OLDAP-2.4\tOpen LDAP Public License v2.4\t0",
	"OLDAP-2.5\tOpen LDAP Public License v2.5\t0",
	"OLDAP-2.6\tOpen LDAP Public License v2.6\t0",
	"OLDAP-2.7\tOpen LDAP Public License v2.7\t2",
	"OLDAP-2.8\tOpen LDAP Public License v2.8\t1",
	"OLFL-1.3\tOpen Logistics Foundation License Version 1.3\t1",
	"OML\tOpen Market License\t0",
	"OPL-1.0\tOpen Public License v1.0\t0",
	"OPL-UK-3.0\tUnited    Kingdom Open Parliament Licence v3.0\t0",
	"OPUBL-1.0\tOpen Publication License v1.0\t0",
	"OSC-1.0\tOSC License 1.0\t1",
	"OSET-PL-2.1\tOSET Public License version 2.1\t1",
	"OSL-1.0\tOpen Software License 1.0\t3",
	"OSL-1.1\tOpen Software License 1.1\t2",
	"OSL-2.0\tOpen Software License 2.0\t3",
	"OSL-2.1\tOpen Software License 2.1\t3",
	"OSL-3.0\tOpen Software License 3.0\t3",
	"OSSP\tOSSP License\t0",
	"OpenMDW-1.0\tOpenMDW License Agreement v1.0\t0",
	"OpenPBS-2.3\tOpenPBS v2.3 Software License\t0",
	"OpenSSL\tOpenSSL License\t2",
	"OpenSSL-standalone\tOpenSSL License - standalone\t0",
	"OpenVision\tOpenVision License\t0",
	"PADL\tPADL License\t0",
	"PDDL-1.0\tOpen Data Commons Public Domain Dedication & License 1.0\t0",
	"PHP-3.0\tPHP License v3.0\t1",
	"PHP-3.01\tPHP License v3.01\t3",
	"PPL\tPeer Production License\t0",
	"PSF-2.0\tPython Software Foundation License 2.0\t0",
	"ParaType-Free-Font-1.3\tParaType Free Font Licensing Agreement v1.3\t0",
	"Parity-6.0.0\tThe Parity Public License 6.0.0\t0",
	"Parity-7.0.0\tThe Parity Public License 7.0.0\t0",
	"Pixar\tPixar License\t0",
	"Plexus\tPlexus Classworlds License\t0",
	"PolyForm-Noncommercial-1.0.0\tPolyForm Noncommercial License 1.0.0\t0",
	"PolyForm-Small-Business-1.0.0\tPolyForm Small Business License 1.0.0\t0",
	"PostgreSQL\tPostgreSQL License\t1",
	"Python-2.0\tPython License 2.0\t3",
	"Python-2.0.1\tPython License 2.0.1\t0",
	"QPL-1.0\tQ Public License 1.0\t3",
	"QPL-1.0-INRIA-2004\tQ Public License 1.0 - INRIA 2004 variant\t0",
	"Qhull\tQhull License\t0",
	"RHeCos-1.1\tRed Hat eCos Public License v1.1\t0",
	"RPL-1.1\tReciprocal Public License 1.1\t1",
	"RPL-1.5\tReciprocal Public License 1.5\t1",
	"RPSL-1.0\tRealNetworks Public Source License v1.0\t3",
	"RSA-MD\tRSA Message-Digest License\t0",
	"RSCPL\tRicoh Source Code Public License\t1",
	"Rdisc\tRdisc License\t0",
	"Ruby\tRuby License\t2",
	"Ruby-pty\tRuby pty extension license\t0",
	"SAX-PD\tSax Public Domain Notice\t0",
	"SAX-PD-2.0\tSax Public Domain Notice 2.0\t0",
	"SCEA\tSCEA Shared Source License\t0",
	"SGI-B-1.0\tSGI Free Software License B v1.0\t0",
	"SGI-B-1.1\tSGI Free Software License B v1.1\t0",
	"SGI-B-2.0\tSGI Free Software License B v2.0\t2",
	"SGI-OpenGL\tSGI OpenGL License\t0",
	"SGMLUG-PM\tSGMLUG Parser Materials License\t0",
	"SGP4\tSGP4 Permission Notice\t0",
	"SHL-0.5\tSolderpad Hardware License v0.5\t0",
	"SHL-0.51\tSolderpad Hardware License, Version 0.51\t0",
	"SISSL\tSun Industry Standards Source License v1.1\t3",
	"SISSL-1.2\tSun Industry Standards Source License v1.2\t0",
	"SL\tSL License\t0",
	"SMAIL-GPL\tSMAIL General Public License\t0",
	"SMLNJ\tStandard ML of New Jersey License\t2",
	"SMPPL\tSecure Messaging Protocol Public License\t0",
	"SNIA\tSNIA Public License 1.1\t0",
	"SOFA\tSOFA Software License\t0",
	"SPL-1.0\tSun Public License v1.0\t3",
	"SSH-OpenSSH\tSSH OpenSSH license\t0",
	"SSH-short\tSSH short notice\t0",
	"SSLeay-standalone\tSSLeay License - standalone\t0",
	"SSPL-1.0\tServer Side Public License, v 1\t0",
	"SUL-1.0\tSustainable Use License v1.0\t0",
	"SWL\tScheme Widget Library (SWL) Software License Agreement\t0",
	"Saxpath\tSaxpath License\t0",
	"SchemeReport\tScheme Language Report License\t0",
	"Sendmail\tSendmail License\t0",
	"Sendmail-8.23\tSendmail License 8.23\t0",
	"Sendmail-Open-Source-1.1\tSendmail Open Source License v1.1\t0",
	"SimPL-2.0\tSimple Public License 2.0\t1",
	"Sleepycat\tSleepycat License\t3",
	"Soundex\tSoundex License\t0",
	"Spencer-86\tSpencer License 86\t0",
	"Spencer-94\tSpencer License 94\t0",
	"Spencer-99\tSpencer License 99\t0",
	"StandardML-NJ\tStandard ML of New Jersey License\t2",
	"SugarCRM-1.1.3\tSugarCRM Public License v1.1.3\t0",
	"Sun-PPP\tSun PPP License\t0",
	"Sun-PPP-2000\tSun PPP License (2000)\t0",
	"SunPro\tSunPro License\t0",
	"Symlinks\tSymlinks License\t0",
	"TAPR-OHL-1.0\tTAPR Open Hardware License v1.0\t0",
	"TCL\tTCL/TK License\t0",
	"TCP-wrappers\tTCP Wrappers License\t0",
	"TGPPL-1.0\tTransitive Grace Period Public Licence 1.0\t0",
	"TMate\tTMate Open Source License\t0",
	"TORQUE-1.1\tTORQUE v2.5+ Software License v1.1\t0",
	"TOSL\tTrusster Open Source License\t0",
	"TPDL\tTime::ParseDate License\t0",
	"TPL-1.0\tTHOR Public License 1.0\t0",
	"TTWL\tText-Tabs+Wrap License\t0",
	"TTYP0\tTTYP0 License\t0",
	"TU-Berlin-1.0\tTechnische Universitaet Berlin License 1.0\t0",
	"TU-Berlin-2.0\tTechnische Universitaet Berlin License 2.0\t0",
	"TekHVC\tTekHVC License\t0",
	"TermReadKey\tTermReadKey License\t0",
	"ThirdEye\tThirdEye License\t0",
	"TrustedQSL\tTrustedQSL License\t0",
	"UCAR\tUCAR License\t0",
	"UCL-1.0\tUpstream Compatibility License v1.0\t1",
	"UMich-Merit\tMichigan/Merit Networks License\t0",
	"UPL-1.0\tUniversal Permissive License v1.0\t3",
	"URT-RLE\tUtah Raster Toolkit Run Length Encoded License\t0",
	"Ubuntu-font-1.0\tUbuntu Font Licence v1.0\t0",
	"UnRAR\tUnRAR License\t0",
	"Unicode-3.0\tUnicode License v3\t1",
	"Unicode-DFS-2015\tUnicode License Agreement - Data Files and Software (2015)\t0",
	"Unicode-DFS-2016\tUnicode License Agreement - Data Files and Software (2016)\t1",
	"Unicode-TOU\tUnicode Terms of Use\t0",
	"UnixCrypt\tUnixCrypt License\t0",
	"Unlicense\tThe Unlicense\t3",
	"Unlicense-libtelnet\tUnlicense - libtelnet variant\t0",
	"Unlicense-libwhirlpool\tUnlicense - libwhirlpool variant\t0",
	"VOSTROM\tVOSTROM Public License for Open Source\t0",
	"VSL-1.0\tVovida Software License v1.0\t1",
	"Vim\tVim License\t2",
	"Vixie-Cron\tVixie Cron License\t0",
	"W3C\tW3C Software Notice and License (2002-12-31)\t3",
	"W3C-19980720\tW3C Software Notice and License (1998-07-20)\t0",
	"W3C-20150513\tW3C Software Notice and Document License (2015-05-13)\t1",
	"WTFNMFPL\tDo What The F*ck You Want To But It's Not My Fault Public License\t0",
	"WTFPL\tDo What The F*ck You Want To Public License\t2",
	"Watcom-1.0\tSybase Open Watcom Public License 1.0\t1",
	"Widget-Workshop\tWidget Workshop License\t0",
	"WordNet\tWordNet License\t1",
	"Wsuipa\tWsuipa License\t0",
	"X11\tX11 License\t2",
	"X11-distribute-modifications-variant\tX11 License Distribution Modification Variant\t0",
	"X11-no-permit-persons\tX11 no permit persons clause\t0",
	"X11-swapped\tX11 swapped final paragraphs\t0",
	"XFree86-1.1\tXFree86 License 1.1\t2",
	"XSkat\tXSkat License\t0",
	"Xdebug-1.03\tXdebug License v 1.03\t0",
	"Xerox\tXerox License\t0",
	"Xfig\tXfig License\t0",
	"Xnet\tX.Net License\t1",
	"YPL-1.0\tYahoo! Public License v1.0\t0",
	"YPL-1.1\tYahoo! Public License v1.1\t2",
	"ZPL-1.1\tZope Public License 1.1\t0",
	"ZPL-2.0\tZope Public License 2.0\t3",
	"ZPL-2.1\tZope Public License 2.1\t3",
	"Zed\tZed License\t0",
	"Zeeff\tZeeff License\t0",
	"Zend-2.0\tZend License v2.0\t2",
	"Zimbra-1.3\tZimbra Public License v1.3\t2",
	"Zimbra-1.4\tZimbra Public License v1.4\t0",
	"Zlib\tzlib License\t3",
	"any-OSI\tAny OSI License\t0",
	"any-OSI-perl-modules\tAny OSI License - Perl Modules\t0",
	"bcrypt-Solar-Designer\tbcrypt Solar Designer License\t0",
	"blessing\tSQLite Blessing\t0",
	"bzip2-1.0.5\tbzip2 and libbzip2 License v1.0.5\t0",
	"bzip2-1.0.6\tbzip2 and libbzip2 License v1.0.6\t0",
	"check-cvs\tcheck-cvs License\t0",
	"checkmk\tCheckmk License\t0",
	"copyleft-next-0.3.0\tcopyleft-next 0.3.0\t0",
	"copyleft-next-0.3.1\tcopyleft-next 0.3.1\t0",
	"curl\tcurl License\t0",
	"cve-tou\tCommon Vulnerability Enumeration ToU License\t0",
	"diffmark\tdiffmark license\t0",
	"dtoa\tDavid M. Gay dtoa License\t0",
	"dvipdfm\tdvipdfm License\t0",
	"eCos-2.0\teCos license version 2.0\t2",
	"eGenix\teGenix.com Public License 1.1.0\t0",
	"etalab-2.0\tEtalab Open License 2.0\t0",
	"fwlw\tfwlw License\t0",
	"gSOAP-1.3b\tgSOAP Public License v1.3b\t0",
	"generic-xts\tGeneric XTS License\t0",
	"gnuplot\tgnuplot License\t2",
	"gtkbook\tgtkbook License\t0",
	"hdparm\thdparm License\t0",
	"hyphen-bulgarian\thyphen-bulgarian License\t0",
	"iMatix\tiMatix Standard Function Library Agreement\t2",
	"jove\tJove License\t0",
	"libpng-1.6.35\tPNG Reference Library License v1 (for libpng 0.5 through 1.6.35)\t0",
	"libpng-2.0\tPNG Reference Library version 2\t0",
	"libselinux-1.0\tlibselinux public domain notice\t0",
	"libtiff\tlibtiff License\t0",
	"libutil-David-Nugent\tlibutil David Nugent License\t0",
	"lsof\tlsof License\t0",
	"magaz\tmagaz License\t0",
	"mailprio\tmailprio License\t0",
	"man2html\tman2html License\t0",
	"metamail\tmetamail License\t0",
	"mpi-permissive\tmpi Permissive License\t0",
	"mpich2\tmpich2 License\t0",
	"mplus\tmplus Font License\t0",
	"ngrep\tngrep License\t0",
	"pkgconf\tpkgconf License\t0",
	"pnmstitch\tpnmstitch License\t0",
	"psfrag\tpsfrag License\t0",
	"psutils\tpsutils License\t0",
	"python-ldap\tPython ldap License\t0",
	"radvd\tradvd License\t0",
	"snprintf\tsnprintf License\t0",
	"softSurfer\tsoftSurfer License\t0",
	"ssh-keyscan\tssh-keyscan License\t0",
	"swrule\tswrule License\t0",
	"threeparttable\tthreeparttable License\t0",
	"ulem\tulem License\t0",
	"w3m\tw3m License\t0",
	"wwl\tWWL License\t0",
	"wxWindows\twxWindows Library License\t1",
	"xinetd\txinetd License\t2",
	"xkeyboard-config-Zinoviev\txkeyboard-config Zinoviev License\t0",
	"xlock\txlock License\t0",
	"xpp\tXPP License\t0",
	"xzoom\txzoom License\t0",
	"zlib-acknowledgement\tzlib/libpng License with Acknowledgement\t0",
	// spdx:license-meta:end
];

/**
 * Metadata for every cataloged SPDX license id, active and deprecated, keyed
 * by identifier. A `LicenseRef`/`DocumentRef` reference is not a catalog
 * member and has no entry.
 *
 * @internal
 */
export const LICENSE_META: ReadonlyMap<string, LicenseMetaEntry> = new Map(
	LICENSE_META_ROWS.map((row) => {
		const tab = row.indexOf("\t");
		const last = row.lastIndexOf("\t");
		const id = row.slice(0, tab);
		return [id, [id, row.slice(tab + 1, last), Number(row.slice(last + 1))] as LicenseMetaEntry] as const;
	}),
);
