# Generated by pluginfinity. Do not edit.
_PF_TOOLS=''
_PF_TOOLS_PLUGIN='effected'
_PF_TOOLS_MCP='mcp__plugin_{plugin}_{server}__{tool}'
_PF_TOOLS_SERVERS=''
_PF_TOOLS_UNLISTED=keep
_PF_HAS_SKILLS='actions-cache-and-artifacts actions-inputs-outputs actions-reporting actions-runtime actions-state-and-secrets bootstrapping-an-action building-a-format-package building-a-github-action building-schemastore-schemas design-patterns designing-an-action effect-api-extractor-bases effect-v4-cli effect-v4-house-style effect-v4-idioms effect-v4-mcp effect-v4-module-index effect-v4-observability effect-v4-planning effect-v4-schema effect-v4-services-layers effect-v4-source-lookup effect-v4-testing effected-packages github-api github-app-tokens hardening-a-parser-port release-and-publish running-commands-and-tools structuring-an-action supply-chain-attestation testing-actions'
_PF_HAS_AGENTS='action-engineer effect-developer effect-reviewer'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS=''
