/**
 * One-off generator for `src/internal/entityMap.ts`.
 *
 * Run by hand, never by CI and never by the test suite:
 *
 * ```sh
 * pnpm --filter @effected/markdown exec tsx __test__/tools/generate-entities.ts
 * ```
 *
 * The HTML5 named character references are WHATWG data, published as a JSON
 * document alongside the HTML standard. This fetches that document directly
 * and keeps only the semicolon-terminated names: CommonMark's entity grammar
 * requires the semicolon, so the legacy unterminated forms can never match.
 *
 * It used to flatten the packed binary trie inside the `entities` npm
 * package instead. That trie is a private structure that re-encodes across
 * releases (8.1.0 did so in a minor), so every bump broke the walker; the
 * spec document is the source `entities` itself builds from, and its shape
 * is a public contract.
 *
 * The generated file is committed; nothing at runtime depends on the fetch.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = "https://html.spec.whatwg.org/entities.json";

/** The document's shape: `&name;` keys, each with its replacement string. */
type EntitiesDocument = Readonly<Record<string, { readonly characters: string }>>;

const response = await fetch(SOURCE);
if (!response.ok) {
	throw new Error(`${SOURCE}: ${response.status} ${response.statusText}`);
}
const document = (await response.json()) as EntitiesDocument;

const entries = Object.entries(document)
	.filter(([name]) => name.endsWith(";"))
	.map(([name, { characters }]) => [name.slice(1, -1), characters] as const)
	.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const fetchedOn = new Date().toISOString().slice(0, 10);

const header = `// Generated by __test__/tools/generate-entities.ts — do not edit by hand.
//
// The HTML5 named character references, from the WHATWG HTML standard's
// entity document (${SOURCE}, fetched ${fetchedOn});
// the human-readable table is at
// https://html.spec.whatwg.org/multipage/named-characters.html.
//
// Only the semicolon-terminated names are here: CommonMark's entity grammar
// requires the semicolon, so the legacy unterminated forms cannot match.
//
// Stored as JSON and parsed once at module load — a ${entries.length}-entry
// Map literal costs several times this in source size, and the parse is a
// one-off. Leaf module: imports nothing.

const DATA = ${JSON.stringify(JSON.stringify(entries))};

/** The HTML5 named character references, keyed without \`&\` or \`;\`. */
export const ENTITY_MAP: ReadonlyMap<string, string> = new Map(JSON.parse(DATA) as ReadonlyArray<[string, string]>);
`;

const target = resolve(import.meta.dirname, "../../src/internal/entityMap.ts");
writeFileSync(target, header);
console.log(`wrote ${entries.length} entities to ${target}`);
