/**
 * One-off generator for `src/internal/entityMap.ts`.
 *
 * Run by hand, never by CI and never by the test suite:
 *
 * ```sh
 * pnpm --filter @effected/markdown exec tsx __test__/tools/generate-entities.ts
 * ```
 *
 * The HTML5 named character references are WHATWG data. `entities` ships them
 * as a packed binary trie rather than a plain map (`dist/*.
 * /generated/decode-data-html.js`), so this walks that trie and flattens it
 * back into name/value pairs. Only the semicolon-terminated names are kept:
 * CommonMark's entity grammar requires the semicolon, so the legacy
 * unterminated forms can never match.
 *
 * `entities` is an exact-pinned devDependency and exists only for this script.
 * The generated file is committed; nothing at runtime depends on the package.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { htmlDecodeTree } from "entities/decode";

/** Bit layout of a trie node, from the `entities` source (`src/decode.ts`). */
const VALUE_LENGTH = 0b1100_0000_0000_0000;
const BRANCH_LENGTH = 0b0011_1111_1000_0000;
const JUMP_TABLE = 0b0000_0000_0111_1111;

const SEMICOLON = 0x3b;

const at = (index: number): number => htmlDecodeTree[index] ?? 0;

/**
 * The decoded replacement string stored at `node`, per the `entities`
 * decoder's `emitNamedEntityData`: one codepoint packed into the node word,
 * one in the next word, or two in the next two.
 */
const valueAt = (node: number, valueLength: number): string => {
	if (valueLength === 1) {
		return String.fromCodePoint(at(node) & ~VALUE_LENGTH);
	}
	if (valueLength === 2) {
		return String.fromCodePoint(at(node + 1));
	}
	return String.fromCodePoint(at(node + 1), at(node + 2));
};

/** Every `(character, childNode)` edge leaving `node`. */
const edgesOf = (node: number): ReadonlyArray<readonly [char: number, child: number]> => {
	const current = at(node);
	const valueLength = (current & VALUE_LENGTH) >> 14;

	// A value length of 1 means the codepoint is packed into the low 14 bits
	// of the node word itself — the same bits that would otherwise hold the
	// branch count and jump offset. Such a node is therefore always terminal;
	// reading branch metadata out of a codepoint walks into garbage.
	if (valueLength === 1) {
		return [];
	}

	const branchesAt = node + Math.max(1, valueLength);
	const branchCount = (current & BRANCH_LENGTH) >> 7;
	const jumpOffset = current & JUMP_TABLE;

	// A single branch, with the character encoded in the jump offset itself.
	if (branchCount === 0) {
		return jumpOffset === 0 ? [] : [[jumpOffset, branchesAt]];
	}

	const edges: Array<readonly [number, number]> = [];

	// A jump table: one slot per character in a contiguous range.
	if (jumpOffset !== 0) {
		for (let index = 0; index < branchCount; index += 1) {
			const child = at(branchesAt + index) - 1;
			if (child >= 0) {
				edges.push([jumpOffset + index, child]);
			}
		}
		return edges;
	}

	// A dictionary: sorted characters, then the matching child indices.
	for (let index = 0; index < branchCount; index += 1) {
		edges.push([at(branchesAt + index), at(branchesAt + branchCount + index)]);
	}
	return edges;
};

const collect = (): ReadonlyArray<readonly [name: string, value: string]> => {
	const entries: Array<readonly [string, string]> = [];

	// Iterative DFS: the trie is ~2000 nodes deep-ish in principle, and an
	// explicit stack keeps the generator honest about the same recursion
	// discipline the engine follows.
	const stack: Array<readonly [node: number, name: string]> = [[0, ""]];

	while (stack.length > 0) {
		const frame = stack.pop();
		if (frame === undefined) {
			break;
		}
		const [node, name] = frame;

		for (const [char, child] of edgesOf(node)) {
			const childName = name + String.fromCharCode(char);
			const childValueLength = (at(child) & VALUE_LENGTH) >> 14;

			// A value reached by consuming `;` is a complete named reference.
			if (childValueLength !== 0 && char === SEMICOLON) {
				entries.push([childName.slice(0, -1), valueAt(child, childValueLength)]);
			}
			stack.push([child, childName]);
		}
	}

	entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
	return entries;
};

const entries = collect();

const header = `// Generated by __test__/tools/generate-entities.ts — do not edit by hand.
//
// The HTML5 named character references, flattened out of the packed trie in
// entities@6.0.1 (https://github.com/fb55/entities), MIT licensed. The data
// itself is the WHATWG HTML named character reference set
// (https://html.spec.whatwg.org/multipage/named-characters.html).
//
// Only the semicolon-terminated names are here: CommonMark's entity grammar
// requires the semicolon, so the legacy unterminated forms cannot match.
//
// Stored as JSON and parsed once at module load — a ${entries.length}-entry
// Map literal costs several times this in source size, and the parse is a
// one-off. Leaf module: imports nothing.

const DATA = ${JSON.stringify(JSON.stringify(entries))};

/** The HTML5 named character references, keyed without \`&\` or \`;\`. */
export const ENTITY_MAP: ReadonlyMap<string, string> = new Map(JSON.parse(DATA) as ReadonlyArray<[string, string]>);
`;

const target = resolve(import.meta.dirname, "../../src/internal/entityMap.ts");
writeFileSync(target, header);
console.log(`wrote ${entries.length} entities to ${target}`);
